create table alma.pool (
    pool_id integer not null generated by default as identity,
    bezeichnung text not null,
    bemerkungen text,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    constraint pk_pool primary key (pool_id),
    constraint uq_pool_art_bezeichnung unique (bezeichnung)
);

comment on table alma.pool is 'Ein Pool entspricht einer manuellen Gruppierung von Standorten';
comment on column alma.pool.pool_id is 'Primary Key';
comment on column alma.pool.bezeichnung is 'Bezeichnung';
comment on column alma.pool.bemerkungen is 'Bemerkung';
comment on column alma.pool.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.pool.erfasser is 'Erfasser';
comment on column alma.pool.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.pool.mutierer is 'Bearbeiter der letzten Aenderung';

create table alma.vfl_pool (
    vfl_pool_id integer not null generated by default as identity,
    pool_id integer not null,
    vfl_id integer not null,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    constraint pk_vfl_pool primary key (vfl_pool_id),
    constraint uq_vfl_pool_pool_id_vfl_id unique (pool_id, vfl_id),
    constraint fk_pool_vfl_pool_vfl_id foreign key (pool_id) references alma.pool(pool_id) on delete cascade on update cascade
);

create index ix_vfl_pool_pool_id on alma.vfl_pool using btree (pool_id);
create index ix_vfl_pool_vfl_id on alma.vfl_pool using btree (vfl_id);

comment on table alma.vfl_pool is 'Zuweisung der Standorte zu Pools. Ein Pool entspricht einer manuellen Gruppierung von Standorten';
comment on column alma.vfl_pool.vfl_pool_id is 'Primary Key';
comment on column alma.vfl_pool.pool_id is 'Foreign Key auf Pool';
comment on column alma.vfl_pool.vfl_id is 'Foreign Key auf Standort. Nicht auf Standortsversion VFLZ sondern unabhängig der Version auf den Standort.';
comment on column alma.vfl_pool.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.vfl_pool.erfasser is 'Erfasser';
comment on column alma.vfl_pool.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.vfl_pool.mutierer is 'Bearbeiter der letzten Aenderung';
