create table alma.c_cli (
    c_cli_id integer not null,
    bezeichnung character varying,
    c_status boolean,
    erfassungs_datum timestamp without time zone default now(),
    erfasser character varying default "current_user"(),
    mutations_datum timestamp without time zone,
    mutierer text,
    constraint pk_c_cli_c_cli_id primary key (c_cli_id)
);

comment on table alma.c_cli is 'Kategorien von Codes / Codelisten. Der Schluessel der Kategorien ist c_cli_id. Alle Datenbankfelder, die Codes aus der zentralen 
    Codeliste enthalten, beginnen mit c_*. Dazu gehoert ein Feld mit Praefix h_*. In die Felder h_* wird der Schluessel aus c_cli eingetragen.';

comment on column alma.c_cli.c_cli_id IS 'primary key; Codelisten ID';
comment on column alma.c_cli.bezeichnung IS 'Bezeichnung der Codeliste';
comment on column alma.c_cli.c_status IS 'Status zur aktiven Verwendung einer Codeliste';
comment on column alma.c_cli.erfassungs_datum is 'Erfassungs-Datum';
comment on column alma.c_cli.erfasser is 'Erfasser';
comment on column alma.c_cli.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.c_cli.mutierer is 'Bearbeiter der letzten Aenderung';


create table alma.cod (
    c_cli_id integer not null,
    code character varying(20) not null,
    sort_key smallint,
    bemerkungen character varying,
    c_status boolean default true not null,
    c_is_null_code boolean default false not null,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    constraint pk_cod_c_cli_id_code primary key (c_cli_id, code),
    constraint fk_c_cli_cod_c_cli_id foreign key (c_cli_id) references alma.c_cli(c_cli_id) on update restrict on delete restrict,
    constraint ex_cod_c_cli_id_c_is_null_code_true exclude (c_cli_id with =) where (c_is_null_code = true)
);

comment on table alma.cod is 'Zentrale Codeliste';

comment on column alma.cod.c_cli_id IS 'primary key; Codelisten ID';
comment on column alma.cod.code IS 'primary key; Codewert';
comment on column alma.cod.sort_key IS 'Sortierung der Codewerte innerhalb der Liste';
comment on column alma.cod.bemerkungen IS 'Bemerkungen zum Code';
comment on column alma.cod.c_status IS 'Status zur aktiven Verwendung eines Codes';
comment on column alma.cod.erfassungs_datum is 'Erfassungs-Datum';
comment on column alma.cod.erfasser is 'Erfasser';
comment on column alma.cod.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.cod.mutierer is 'Bearbeiter der letzten Aenderung';


create table alma.cod_kbsinfo (
    cod_kbsinfo_id integer not null generated by default as identity,
    h_bere_res_abwbewe integer default 103 not null,
    c_bere_res_abwbewe character varying(8) not null,
    color character varying(7) not null default '#000000'::character varying,
    color_rgb character varying(11) default '0 0 0'::character varying,
    belastet boolean not null,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    constraint fki_cod_berekbs_c_ber_res_abwbewe_cod foreign key (c_bere_res_abwbewe, h_bere_res_abwbewe) references alma.cod(code, c_cli_id) on delete cascade,
    constraint pk_cod_kbsinfo_cod_kbsinfo_id primary key (cod_kbsinfo_id),
    constraint uq_cod_kbsinfo_bere_res_bwbewe unique (h_bere_res_abwbewe, c_bere_res_abwbewe)
);

comment on table alma.cod_kbsinfo is 'Kbs information for display of standort';
comment on column alma.cod_kbsinfo.cod_kbsinfo_id is 'primary key';
comment on column alma.cod_kbsinfo.h_bere_res_abwbewe is 'foreign key: Codeliste Bewertung';
comment on column alma.cod_kbsinfo.c_bere_res_abwbewe is 'foreign key: Code Bewertung';
comment on column alma.cod_kbsinfo.color is 'Color as hexadecimal value with leading #';
comment on column alma.cod_kbsinfo.color_rgb is 'Color as RGB values (base 10), separated by spaces. used by mapserver.';
comment on column alma.cod_kbsinfo.belastet is 'True, wenn Beurteilungs-Code als Belastet gilt. Nur ein belasteter Standort kann in Kataster belasteter Standorte(KBS) veröffentlicht werden.';
comment on column alma.cod_kbsinfo.erfassungs_datum is 'Erfassungs-Datum';
comment on column alma.cod_kbsinfo.erfasser is 'Erfasser';
comment on column alma.cod_kbsinfo.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.cod_kbsinfo.mutierer is 'Bearbeiter der letzten Aenderung';


create table alma.cod_bezart (
    cod_bezart_id integer not null generated by default as identity,
    is_eigentuemer boolean default false not null,
    h_bez_art integer default 22 not null,
    c_bez_art text,
    constraint pk_cod_bezart_id primary key(cod_bezart_id)
);
comment on table alma.cod_bezart is 'Zusatzinfos zu Codes Beziehungsart';
comment on column alma.cod_bezart.cod_bezart_id is 'Primary Key.';
comment on column alma.cod_bezart.is_eigentuemer is 'Legt fest ob die Beziehungsart ein Eigentum darstellt oder nicht.';
comment on column alma.cod_bezart.h_bez_art is 'Codeliste Beziehungsart Subjekt/Objekt';
comment on column alma.cod_bezart.c_bez_art is 'Code Beziehungsart Subjekt/Objekt';


create table alma.translations (
    msgid character varying not null,
    msgstr character varying not null,
    locale character varying not null,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    constraint translations_msgid_locale primary key (msgid, locale),

    --
    -- Special constraints for translations of search fields
    --

    -- Search fields must not contain whitespace
    constraint check_search_field_ws check (
        (msgid not like 'search.field.%') or (msgstr !~ '\s')
    ),

    -- Translations for search fields must be unique within the same language
    constraint ex_search_field_same_lang exclude using gist (
        -- exclude if an entry exists with
        locale with =,          -- same language
        (lower(msgstr)) with =  -- same translation (case insensitive)
    ) where (msgid like 'search.field.%'),

    -- Two search fields cannot have the same translation in different languages
    constraint ex_search_field_diff_lang exclude using gist (
        -- exclude if an entry exists with
        (lower(msgstr)) with =,  -- same translation (case insensitive)
        msgid with !=            -- different search field
    ) where (msgid like 'search.field.%'),

    --
    -- Special constraints for translations of code values
    --

    -- Translations within the same code list must be unique within the same language
    constraint ex_code_c_cli_id_same_lang exclude using gist (
        -- exclude if an entry exists with
        ((string_to_array(msgid, ':'))[2]) with =,   -- same c_cli_id
        locale with =,                               -- same language
        (lower(msgstr)) with =                       -- same translation (case insensitive)
    ) where (msgid like 'code:%:%'),

    -- Within the same code list, two codes cannot have the same translation in different languages
    constraint ex_code_c_cli_id_diff_lang exclude using gist (
        -- exclude if an entry exists with
        ((string_to_array(msgid, ':'))[2]) with =,  -- same c_cli_id
        (lower(msgstr)) with =,                     -- same translation (case insensitive)
        ((string_to_array(msgid, ':'))[3]) with !=  -- different code
    ) where (msgid like 'code:%:%'),

    -- For certain groups of code list, the translations must be unique across
    -- the entire group, when codes from all lists in the group are valid
    -- values for the same field.

    constraint ex_code_c_cli_id_same_lang_stoffgruppe exclude using gist (
        -- exclude if an entry exists with
        locale with =,          -- same language
        (lower(msgstr)) with =  -- same translation (case insensitive)
    ) where (
        msgid like 'code:%:%'
        and (string_to_array(msgid, ':'))[2]::integer between 110 and 115
    ),
    constraint ex_code_c_cli_id_diff_lang_stoffgruppe exclude using gist (
        -- exclude if an entry exists with
        (lower(msgstr)) with =,                        -- same translation (case insensitive)
        (regexp_replace(msgid, '^code:', '')) with !=  -- different c_cli_id + code
    ) where (
        msgid like 'code:%:%'
        and (string_to_array(msgid, ':'))[2]::integer between 110 and 115
    ),

    constraint ex_code_c_cli_id_same_lang_stoff exclude using gist (
        -- exclude if an entry exists with
        locale with =,          -- same language
        (lower(msgstr)) with =  -- same translation (case insensitive)
    ) where (
        msgid like 'code:%:%'
        and (string_to_array(msgid, ':'))[2]::integer between 301 and 309
    ),
    constraint ex_code_c_cli_id_diff_lang_stoff exclude using gist (
        -- exclude if an entry exists with
        (lower(msgstr)) with =,                        -- same translation (case insensitive)
        (regexp_replace(msgid, '^code:', '')) with !=  -- different c_cli_id + code
    ) where (
        msgid like 'code:%:%'
        and (string_to_array(msgid, ':'))[2]::integer between 301 and 309
    ),

    constraint ex_code_c_cli_id_same_lang_nutzung exclude using gist (
        -- exclude if an entry exists with
        locale with =,          -- same language
        (lower(msgstr)) with =  -- same translation (case insensitive)
    ) where (
        msgid like 'code:%:%'
        and (string_to_array(msgid, ':'))[2]::integer in (83, 92, 104)
    ),
    constraint ex_code_c_cli_id_diff_lang_nutzung exclude using gist (
        -- exclude if an entry exists with
        (lower(msgstr)) with =,                        -- same translation (case insensitive)
        (regexp_replace(msgid, '^code:', '')) with !=  -- different c_cli_id + code
    ) where (
        msgid like 'code:%:%'
        and (string_to_array(msgid, ':'))[2]::integer in (83, 92, 104)
    ),

    constraint ex_code_c_cli_id_same_lang_schaeden exclude using gist (
        -- exclude if an entry exists with
        locale with =,          -- same language
        (lower(msgstr)) with =  -- same translation (case insensitive)
    ) where (
        msgid like 'code:%:%'
        and (string_to_array(msgid, ':'))[2]::integer in (99, 100, 102)
    ),
    constraint ex_code_c_cli_id_diff_lang_schaeden exclude using gist (
        -- exclude if an entry exists with
        (lower(msgstr)) with =,                        -- same translation (case insensitive)
        (regexp_replace(msgid, '^code:', '')) with !=  -- different c_cli_id + code
    ) where (
        msgid like 'code:%:%'
        and (string_to_array(msgid, ':'))[2]::integer in (99, 100, 102)
    )
);

comment on table alma.translations is 'Übersetzungstabelle für für Codelisten';

comment on column alma.translations.msgid IS 'Zusammengesetzter Code: code.c_cli_id.code';
comment on column alma.translations.msgstr IS 'Übersetzung';
comment on column alma.translations.locale IS 'Sprache';
comment on column alma.translations.erfassungs_datum is 'Erfassungs-Datum';
comment on column alma.translations.erfasser is 'Erfasser';
comment on column alma.translations.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.translations.mutierer is 'Bearbeiter der letzten Aenderung';

create index idx_translations_locale on alma.translations using btree (locale);
create index idx_translations_msgid on alma.translations using btree (msgid);
