create table alma.bere (
    vflz_id integer not null,
    h_bere_res_abwbewe integer default 103,
    c_bere_res_abwbewe character varying(8),
    h_bere_prio_untersuch integer default 26020,
    c_bere_prio_untersuch character varying(4),
    h_bere_prio_sanier integer default 26021,
    c_bere_prio_sanier character varying(4),
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint pk_bere_vflz_id primary key (vflz_id),
    constraint fk_vflz_bere_vflz_id foreign key (vflz_id) references alma.vflz(vflz_id) on update cascade on delete cascade,
    constraint bere_h_bere_res_abwbewe_fkey foreign key (h_bere_res_abwbewe) references alma.c_cli(c_cli_id)
);

comment on table alma.bere is 'Beurteilung der Standorte. Bei eine Änderung der Beurteilung wird automatisch eine neue Version angelegt.';

comment on column alma.bere.vflz_id is 'foreign key; alma.vflz';
comment on column alma.bere.h_bere_res_abwbewe is 'Codeliste Beurteilung';
comment on column alma.bere.c_bere_res_abwbewe is 'Code Beurteilung';
comment on column alma.bere.h_bere_prio_untersuch is 'Codeliste Priorisierung Untersuchungsbedarf';
comment on column alma.bere.c_bere_prio_untersuch is 'Code Priorisierung Untersuchungsbedarf, Angabe als Jahreszahl';
comment on column alma.bere.h_bere_prio_sanier is 'Codeliste Priorisierung Überwachungs-/Sanierungsbedarf';
comment on column alma.bere.c_bere_prio_sanier is 'Code Priorisierung Überwachungs-/Sanierungsbedarf, Angabe als Jahreszahl';
comment on column alma.bere.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.bere.erfasser is 'Erfasser';
comment on column alma.bere.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.bere.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.bere.is_current is 'Aktuelle oder historisierte Version';

create index ix_fk_vflz_bere_vflz_id on alma.bere using btree (vflz_id);



create table alma.mass (
    mass_id integer not null generated by default as identity,
    vflz_id integer not null,
    h_massnahme integer default 10021,
    c_massnahme character varying(8),
    dat_massnahme date,
    ang_massnahme date,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint pk_mass_mass_id primary key (mass_id),
    constraint fk_vflz_mass_vflz_id foreign key (vflz_id) references alma.vflz(vflz_id) on update cascade on delete cascade,
    constraint mass_h_massnahme_fkey foreign key (h_massnahme) references alma.c_cli(c_cli_id)
);

comment on table alma.mass is 'Durchgeführte oder angeordnete Massnahmen';

comment on column alma.mass.mass_id is 'primary key';
comment on column alma.mass.vflz_id is 'foreign key; alma.vflz';
comment on column alma.mass.h_massnahme is 'Codeliste Massnahme';
comment on column alma.mass.c_massnahme is 'Code Massnahme';
comment on column alma.mass.dat_massnahme is 'Enddatum der Massnahme';
comment on column alma.mass.ang_massnahme is 'Datum der Anordnung';
comment on column alma.mass.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.mass.erfasser is 'Erfasser';
comment on column alma.mass.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.mass.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.mass.is_current is 'Aktuelle oder historisierte Version';

create index ix_fk_vflz_mass_vflz_id on alma.mass using btree (vflz_id);



create table alma.sani (
    sani_id integer not null generated by default as identity,
    vflz_id integer not null,
    h_saniziel integer default 10020,
    c_saniziel character varying(8),
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint pk_sani_sani_id primary key (sani_id),
    constraint fk_vflz_sani_vflz_id foreign key (vflz_id) references alma.vflz(vflz_id) on update cascade on delete cascade,
    constraint sani_h_saniziel_fkey foreign key (h_saniziel) references alma.c_cli(c_cli_id)

);

comment on table alma.sani is 'Sanierungsziel';

comment on column alma.sani.sani_id is 'primary key';
comment on column alma.sani.vflz_id is 'foreign key; alma.vflz';
comment on column alma.sani.h_saniziel is 'Codeliste Sanierungsziel';
comment on column alma.sani.c_saniziel is 'Code Sanierungsziel';
comment on column alma.sani.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.sani.erfasser is 'Erfasser';
comment on column alma.sani.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.sani.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.sani.is_current is 'Aktuelle oder historisierte Version';

create index idx_sani_vflz_id on alma.sani using btree (vflz_id);
create index ix_fk_vflz_sani_vflz_id on alma.sani using btree (vflz_id);
