create table alma.subj (
    subj_id integer not null generated by default as identity,
    "name" text not null default '',
    vorname text not null default '',
    taetigkeit text not null default '',
    kuerzel text,
    h_land integer default 14,
    c_land text,
    h_anrede integer default 31,
    c_anrede text,
    ident_nr text,
    import_key text,
    ort text not null default '',
    postleitzahl text not null default '',
    strasse text not null default '',
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone default now(),
    mutierer text,
    constraint pk_subj_subj_id primary key (subj_id),
    constraint uq_subj_ident_nr unique (ident_nr),
    constraint uq_subj_import_key unique (import_key)
);
create index idx_subj_subj_id on alma.subj using btree (subj_id);

comment on table alma.subj is 'Subjekte als natuerliche und juristische Personen (Personen, Unternehmen)';
comment on column alma.subj.subj_id is 'Primary key';
comment on column alma.subj.name is 'Nachname der Person';
comment on column alma.subj.vorname is 'Vorname der Person';
comment on column alma.subj.taetigkeit is 'Taetigkeit (Person) oder Name des Unternehmens';
comment on column alma.subj.kuerzel is 'Kuerzel KTU';
comment on column alma.subj.h_land is 'Codeliste Land';
comment on column alma.subj.c_land is 'Code Land';
comment on column alma.subj.h_anrede is 'Codeliste Anrede';
comment on column alma.subj.c_anrede is 'Code Anrede';
comment on column alma.subj.ident_nr is 'Eindeutige Ident-Nr. (Person: AHV-Nr., Unternehmen: UID)';
comment on column alma.subj.import_key is 'Referenzfeld für Datenimport';
comment on column alma.subj.ort is 'Ort';
comment on column alma.subj.postleitzahl is 'Postleitzahl';
comment on column alma.subj.strasse is 'Strasse mit Hausnummer';
comment on column alma.subj.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.subj.erfasser is 'Erfasser';
comment on column alma.subj.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.subj.mutierer is 'Bearbeiter der letzten Aenderung';

create table alma.bet (
    bet_id integer not null generated by default as identity,
    vflz_id integer not null,
    subj_id integer not null,
    is_eigentuemer boolean not null default false,
    is_sachbearbeiter boolean not null default false,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone default now(),
    mutierer text,
    is_current boolean not null default true,
    constraint pk_bet_bet_id primary key (bet_id),
    constraint fk_bet_vflz_id foreign key (vflz_id) references alma.vflz(vflz_id) on delete cascade on update cascade,
    constraint fk_bet_subj_id foreign key (subj_id) references alma.subj(subj_id) on delete cascade on update cascade,
    constraint uq_bet_vflz_id_subj_id unique (vflz_id, subj_id)
);
create index idx_bet_vflz_id on alma.bet using btree (vflz_id);
create index idx_bet_subj_id on alma.bet using btree (subj_id);

comment on table alma.bet is 'Pool aller Beteiligten an einem Standort. Ein Eintrag pro Standort und Subjekt.';
comment on column alma.bet.bet_id is 'Primary Key';
comment on column alma.bet.vflz_id is 'Foreign Key auf Standort';
comment on column alma.bet.subj_id is 'Foreign Key auf Subjekt';
comment on column alma.bet.is_eigentuemer is 'Subjekt ist Eigentümer';
comment on column alma.bet.is_sachbearbeiter is 'Subjekt ist Sachbearbeiter';
comment on column alma.bet.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.bet.erfasser is 'Erfasser';
comment on column alma.bet.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.bet.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.bet.is_current is 'Aktuelle oder historisierte Version';


create table alma.bet_art (
    bet_art_id integer not null generated by default as identity,
    bet_id integer not null,
    grun_id integer,
    h_bez_art integer not null default 2201,
    c_bez_art text not null,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone default now(),
    mutierer text,
    is_current boolean not null default true,
    constraint pk_bet_bet_art_id primary key (bet_art_id),
    constraint fk_bet_art_bet_id foreign key (bet_id) references alma.bet(bet_id) on delete cascade on update cascade,
    constraint fk_bet_art_grun_id foreign key (grun_id) references alma.grun(grun_id) on update cascade,
    constraint chk_bet_art_h_bez_art check (h_bez_art in (2200, 2201, 2202))
);
create index idx_fk_bet_art_bet_id on alma.bet_art using btree (bet_id);

comment on table alma.bet_art is 'Zuordnung von Beteiligten zum Standort (mit oder ohne Parzelle).';
comment on column alma.bet_art.bet_art_id is 'Primary Key';
comment on column alma.bet_art.bet_id is 'Foreign Key auf Beteiligten';
comment on column alma.bet_art.grun_id is 'Foreign Key auf Parzelle (optional)';
comment on column alma.bet_art.h_bez_art is 'Codeliste für Art des Beteiligten.';
comment on column alma.bet_art.c_bez_art is 'Code für Art des Beteiligten.';
comment on column alma.bet_art.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.bet_art.erfasser is 'Erfasser';
comment on column alma.bet_art.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.bet_art.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.bet_art.is_current is 'Aktuelle oder historisierte Version';


create table alma.kontakt (
    kontakt_id integer not null generated by default as identity,
    kontakt text not null,
    h_kontakt_typ integer not null default 33,
    c_kontakt_typ text not null,
    subj_id integer not null,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone default now(),
    mutierer text,
    constraint pk_kontakt_kontakt_id primary key (kontakt_id),
    constraint fk_kontakt_subj_id foreign key (subj_id) references alma.subj(subj_id) on delete cascade on update cascade
);
create index idx_kontakt_c_kontakttyp on alma.kontakt using btree (c_kontakt_typ);
create index idx_kontakt_subj_id on alma.kontakt using btree (subj_id);
create index idx_kontakt_telefonnummer on alma.kontakt using btree (kontakt);

comment on table alma.kontakt is 'Kontaktadressen: Telefon, E-Mail, Webseite, etc.';
comment on column alma.kontakt.kontakt_id is 'Primary Key';
comment on column alma.kontakt.kontakt is 'Kontakt';
comment on column alma.kontakt.h_kontakt_typ is 'Codeliste Kontakt-Typ';
comment on column alma.kontakt.c_kontakt_typ is 'Code Kontakt-Typ';
comment on column alma.kontakt.subj_id is 'Foreign key auf Subjekt';
comment on column alma.kontakt.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.kontakt.erfasser is 'Erfasser';
comment on column alma.kontakt.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.kontakt.mutierer is 'Bearbeiter der letzten Aenderung';


create table alma.grun_subj (
    grun_subj_id integer not null generated by default as identity,
    grun_id integer not null,
    subj_id integer not null,
    h_eigentums_art integer default 2200,
    c_eigentums_art text,
    c_status boolean not null default true,
    bemerkungen text,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone default now(),
    mutierer text,
    constraint fk_grun_subj_grun_id foreign key (grun_id) references alma.grun(grun_id) on delete cascade on update cascade,
    constraint fk_grun_subj_subj_id foreign key (subj_id) references alma.subj(subj_id) on delete cascade
);
create index idx_grun_subj_grun_id on alma.grun_subj using btree (grun_id);
create index idx_grun_subj_subj_id on alma.grun_subj using btree (subj_id);
create index idx_grun_subj_subj_id_grun_id on alma.grun_subj using btree (subj_id, grun_id);


comment on table alma.grun_subj is 'Beteiligte von Parzellen, GrundeigentümerInnen';
comment on column alma.grun_subj.grun_subj_id is 'Primary Key';
comment on column alma.grun_subj.grun_id is 'Foreign Key zur Parzelle';
comment on column alma.grun_subj.subj_id is 'Foreign Key auf Beteiligte';
comment on column alma.grun_subj.h_eigentums_art is 'Codeliste Art des Beteiligtenverhaeltnisses';
comment on column alma.grun_subj.c_eigentums_art is 'Code Art des Beteiligtenverhaeltnisses';
comment on column alma.grun_subj.c_status is 'Aktualität des Eintrags';
comment on column alma.grun_subj.bemerkungen is 'Bemerkungen';
comment on column alma.grun_subj.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.grun_subj.erfasser is 'Erfasser';
comment on column alma.grun_subj.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.grun_subj.mutierer is 'Bearbeiter der letzten Aenderung';


create table alma.subj_category (
    subj_category_id integer not null generated by default as identity,
    subj_id integer not null,
    h_subj_category integer default 10019 not null,
    c_subj_category text not null,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone default now(),
    mutierer text,
    constraint pk_subj_category primary key (subj_category_id),
    constraint fk_subj_category_subj_id foreign key (subj_id) references alma.subj(subj_id) on delete cascade
);

create index idx_subj_category_subj_category_id on alma.subj_category using btree (subj_category_id);
create index idx_subj_category_subj_id on alma.subj_category using btree (subj_id);
create index idx_subj_category_subj_id_subj_category_id on alma.subj_category using btree (subj_id, subj_category_id);

comment on table alma.subj_category is 'Mapping-Tabelle von Kategorien zu Subjekten';
comment on column alma.subj_category.subj_category_id is 'Primary Key';
comment on column alma.subj_category.subj_id is 'Foreign key auf das Subjekt';
comment on column alma.subj_category.h_subj_category is 'Codeliste für die Kategorie';
comment on column alma.subj_category.c_subj_category is 'Code der Kategorie';
comment on column alma.subj_category.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.subj_category.erfasser is 'Erfasser';
comment on column alma.subj_category.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.subj_category.mutierer is 'Bearbeiter der letzten Aenderung';

-- Connect alma users with subj
alter table alma_admin.auth_user add column subj_id integer references alma.subj (subj_id);
comment on column alma_admin.auth_user.subj_id is 'Verknüpfung mit Subjekt in alma für Sachbearbeiter';
