create table alma_export.report (
    report_id integer not null generated by default as identity,
    title text not null,
    template text not null,
    style text not null,
    context text not null,
    is_active boolean default false,
    export_format text default 'PDF',
    constraint pk_report primary key (report_id)
);
create index ix_report_report_id on alma_export.report using btree(report_id);

comment on table alma_export.report is 'Konfiguration von Reporten.';
comment on column alma_export.report.report_id is 'Primary key.';
comment on column alma_export.report.title is 'Key zum Titel des Reports für die Übersetzungen.';
comment on column alma_export.report.template is 'Pfad zur Formatvorlage.';
comment on column alma_export.report.style is 'CSS Datei zur Darstellung.';
comment on column alma_export.report.context is 'Stellen, an denen der Report verfügbar sein soll.';
comment on column alma_export.report.is_active is 'Gibt an ob der Report aktiv ist oder nicht.';
comment on column alma_export.report.export_format is 'Komma-separierte Liste zu den Export-Formaten des Reports.';


create table alma_export.report_sql_query (
    report_sql_query_id integer not null generated by default as identity,
    name text not null,
    description text null,
    query text not null,
    constraint pk_report_sql_query_report_sql_query_id primary key (report_sql_query_id),
    constraint uq_report_sql_query_name unique (name)
);

create index ix_report_sql_query_report_sql_query_id on alma_export.report_sql_query using btree(report_sql_query_id);

comment on table alma_export.report_sql_query is 'Benötigte SQL-Queries zur Reportgenerierung.';
comment on column alma_export.report_sql_query.report_sql_query_id is 'Primary key.';
comment on column alma_export.report_sql_query.name is 'Eineindeutiger Name fuer die Query.';
comment on column alma_export.report_sql_query.description is 'Beschreibung der Query.';
comment on column alma_export.report_sql_query.query is 'Eigentliche Query.';


create table alma_export.report_report_sql_query (
    report_id integer not null,
    report_sql_query_id integer not null,
    constraint pk_report_report_sql_query_id_report_id primary key (report_sql_query_id, report_id),
    constraint fk_report_report_report_report_sql_query foreign key (report_id) references alma_export.report (report_id),
    constraint fk_report_report_sql_query_report_report_sql_query foreign key (report_sql_query_id) references alma_export.report_sql_query (report_sql_query_id)
);

comment on table alma_export.report_report_sql_query is 'Tabelle zum Mapping von Sql Queries zu Reporten.';
comment on column alma_export.report_report_sql_query.report_id is 'Foreign Key zum Report.';
comment on column alma_export.report_report_sql_query.report_sql_query_id is 'Foreign Key zur Sql Query.';

create table alma_export.report_param (
    param_id integer not null generated by default as identity,
    report_id integer not null,
    name text not null,
    type text not null,
    sort_key integer,
    constraint pk_report_param_param_id primary key (param_id),
    constraint uq_report_param_name_report_id unique (name, report_id),
    constraint ck_report_param_type check (type = 'INTEGER' or type = 'BOOL' or type = 'TEXT' or type = 'DATE'),
    constraint fk_report_report_param foreign key (report_id) references alma_export.report (report_id)
);

comment on table alma_export.report_param is 'Notwendige Parameter zur Reportgenerierung.';
comment on column alma_export.report_param.report_id is 'Foreign Key.';
comment on column alma_export.report_param.param_id is 'Primary Key.';
comment on column alma_export.report_param.name is 'Bezeichnung';
comment on column alma_export.report_param.type is 'Typ des Parameters. Zurzeit unterstützt: integer, bool, text und date.';
comment on column alma_export.report_param.sort_key is 'Sorierung der Parameter innerhalb der Parameterliste.'
