create table alma_external.wfs_cache (
    wfs_cache_id integer not null generated by default as identity,
    wkb_geometry public.geometry not null,
    postleitzahl character varying(8),
    ort character varying(100),
    h_gem_id int,
    gemeinde_name text,
    bfs_nummer integer,
    h_nb_id text,
    egrid text,
    gb_nummer text,
    gws_zone text,
    gws_bereich text,
    wfs_service_name text not null,
    created_at timestamp without time zone not null default now(),
    constraint pk_wfs_cache primary key (wfs_cache_id),
    constraint enforce_srid_wkb_geometry check ((public.st_srid(wkb_geometry) = 2056))
);

create index ix_wfs_cache_wfs_cache_id on alma_external.wfs_cache using btree(wfs_cache_id);
create index ix_wfs_cache_geometry on alma_external.wfs_cache using gist(wkb_geometry);

comment on table alma_external.wfs_cache is 'Caching von (nachprozessierten) WFS-Anfragen.';
comment on column alma_external.wfs_cache.wfs_cache_id is 'Primary Key';
comment on column alma_external.wfs_cache.wkb_geometry is 'Extent des WFS-Features';
comment on column alma_external.wfs_cache.postleitzahl is 'Postleitzahl';
comment on column alma_external.wfs_cache.ort is 'Ort';
comment on column alma_external.wfs_cache.h_gem_id is 'Gemeinde ID.';
comment on column alma_external.wfs_cache.gemeinde_name is 'Name der Gemeinde.';
comment on column alma_external.wfs_cache.bfs_nummer is 'BFS Nummer der Gemeinde.';
comment on column alma_external.wfs_cache.h_nb_id is 'Parzelle: Nummierungsbereich';
comment on column alma_external.wfs_cache.egrid is 'Parzelle: EGRID';
comment on column alma_external.wfs_cache.gb_nummer is 'Parzelle: Grundbuchsnummer';
comment on column alma_external.wfs_cache.gws_zone is 'Gewaesserschutzzone.';
comment on column alma_external.wfs_cache.gws_bereich is 'Gewaesserschutzbereich.';
comment on column alma_external.wfs_cache.wfs_service_name is 'Cachender WFS Service.';
comment on column alma_external.wfs_cache.created_at is 'Zeitstempel.';

create table alma_external.wfs_update (
    vflz_id integer not null,
    last_update timestamp without time zone not null,
    constraint pk_wfs_update primary key (vflz_id)
);
create index ix_wfs_update_vflz_id on alma_external.wfs_update using btree(vflz_id);

comment on table alma_external.wfs_update is 'Speichert die letzten Updates der WFS Dienste.';
comment on column alma_external.wfs_update.vflz_id is 'Primary Key, ID des VFLZ.';
comment on column alma_external.wfs_update.last_update is 'Letztes Update des WFS.';

