create table alma.h_nb (
    h_nb_id varchar not null,
    bezeichnung text,
    wkb_geometry geometry(MULTIPOLYGON, 2056),
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone default now(),
    mutierer text,
    constraint pk_h_nb primary key (h_nb_id)
);
create index idx_h_nb_wkb_geometry on alma.h_nb using gist (wkb_geometry);

comment on table alma.h_nb is 'Numerierungsbereiche Parzellen. Eine Parzelle ist durch die Kombination aus Numerierungsbereich und Nummer eindeutig identifiziert';
comment on column alma.h_nb.h_nb_id is 'Numerierungsbereich ID (NBIdent)';
comment on column alma.h_nb.bezeichnung is 'Örtliche Bezeichung (Grundbuch-Name, Sektion, ...)';
comment on column alma.h_nb.wkb_geometry is 'Fläche des Numerierungsbereichs als Polygon. Wird aus den Flächen der dazugheörigen Parzellen berechnet';
comment on column alma.h_nb.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.h_nb.erfasser is 'Erfasser';
comment on column alma.h_nb.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.h_nb.mutierer is 'Bearbeiter der letzten Aenderung';


create table alma.grun (
    grun_id integer not null generated by default as identity,
    h_gem_id integer not null,
    h_nb_id varchar,
    gb_nummer varchar not null,
    egrid varchar,
    h_grun_status integer not null default 26000,
    c_grun_status varchar not null default '1',
    wkb_geometry public.geometry(MULTIPOLYGON, 2056) NULL,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone default now(),
    mutierer text,
    constraint enforce_dims_wkb_geometry check ((st_ndims(wkb_geometry) = 2)),
    constraint enforce_srid_wkb_geometry check ((st_srid(wkb_geometry) = 2056)),
    -- when c_status = '1' then h_nb_id must not be NULL
    --TODO: after import foreign parcel data add the following lines
    -- constraint enforce_h_nb_id_not_null check (not c_grun_status = '1' or h_nb_id is not null),
    constraint pk_grun_grun_id primary key (grun_id)
);
create index idx_grun_wkb_geometry on alma.grun using gist (wkb_geometry);
-- Make sure egrid and h_nb_id+gb_nummer are unique among rows with c_status = '1' (current)
create unique index iq_grun_egrid_is_current on alma.grun using btree (egrid) where c_grun_status = '1';
create unique index iq_grun_h_n_bid_gb_nummer_is_current on alma.grun using btree (h_nb_id, gb_nummer) where c_grun_status = '1';

comment on table alma.grun is 'Parzellen (Grundstücke). Daten werden in der Regel aus externen Diensten bezogen.';
comment on column alma.grun.grun_id is 'Primary key';
comment on column alma.grun.h_gem_id is 'Foreign Key auf h_gem';
comment on column alma.grun.h_nb_id is 'Numerierungsbereich ID (NBIdent)';
comment on column alma.grun.gb_nummer is 'Gemeindeweise Grundbuchnummer';
comment on column alma.grun.egrid is 'EGRID der Parzelle, wenn bekannt';
comment on column alma.grun.h_grun_status is 'Codeliste Aktualität des Grundstücks';
comment on column alma.grun.c_grun_status is 'Codewert Aktualität des Grundstücks';
comment on column alma.grun.wkb_geometry is 'Geometrie des Grundstücks als Polygon.';
comment on column alma.grun.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.grun.erfasser is 'Erfasser';
comment on column alma.grun.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.grun.mutierer is 'Bearbeiter der letzten Aenderung';
