create table alma.wf_config (
    wf_config_id integer not null generated by default as identity,
    key uuid not null,
    workflow_id integer references alma.wf_config(wf_config_id),
    title text not null,
    "type" varchar(100) not null,
    version integer not null default 1,
    time_period integer,
    name text,
    -- Felder Typ workflow
    start_task_id integer references alma.wf_config(wf_config_id),
    -- Felder Typ workflow und task (nur eigenständig)
    min_per_entity integer not null default 0,
    max_per_entity integer,
    -- Felder Typ task
    events jsonb,
    is_start_task boolean,
    -- Felder Typ formular
    fields jsonb,
    -- Felder Type dokument, formular
    is_optional boolean,
    constraint pk_workflow_workflow_id primary key (wf_config_id),
    constraint uq_workflow_key unique (key),
    constraint uq_workflow_id_name unique (workflow_id, name),
    constraint check_type check ("type" in ('workflow', 'task', 'form', 'document'))
);

comment on table alma.wf_config is 'Prozesskonfiguration für vordefinierte Prozesse und Aufgaben';

comment on column alma.wf_config.wf_config_id is 'Primary key';
comment on column alma.wf_config.key is 'Eindeutige ID (Instanz-übergreifend) zum Abgleich bei Import aus Datei';
comment on column alma.wf_config.workflow_id is 'ID des Prozesses, zu dem die Konfiguration gehört';
comment on column alma.wf_config.title is 'Titel Prozess/Aufgabe/Dokument/Formular';
comment on column alma.wf_config."type" is 'Typ des Objekts: workflow/task/form/document';
comment on column alma.wf_config.time_period is 'Frist in Tagen';
comment on column alma.wf_config.start_task_id is 'Prozess: ID der Start-Aufgabe';
comment on column alma.wf_config.min_per_entity is 'Wie oft muss der Prozess, die Aufgabe mindestens pro Standort existieren';
comment on column alma.wf_config.max_per_entity is 'Wie oft darf der Prozess, die Aufgabe maximal pro Standort existieren';
comment on column alma.wf_config.name is 'Formular, Aufgabe: Name für interne Referenzierung';
comment on column alma.wf_config.events is 'Aufgabe: Events beim Abschluss der Aufgabe';
comment on column alma.wf_config.is_start_task is 'Aufgabe: Kann der Prozess bei dieser Aufgabe gestartet werden';
comment on column alma.wf_config.fields is 'Formular: Definition der Formularfelder';
comment on column alma.wf_config.is_optional is 'Formular, Dokument: Schritt ist optional';


create table alma.wf_link (
    task_id integer not null references alma.wf_config(wf_config_id) on delete cascade,
    target_task_id integer not null references alma.wf_config(wf_config_id),
    link_no integer not null default 1,
    condition jsonb,
    constraint pk_wf_link_task_id_target_task_id primary key (task_id, target_task_id),
    constraint wf_link_task_id_link_no unique (task_id, link_no)
);

comment on table alma.wf_link is 'Verknüpfungen zwischen Aufgaben';

comment on column alma.wf_link.task_id is 'Id der Aufgabe in der Tabelle alma.wf_config';
comment on column alma.wf_link.target_task_id is 'Id der Folge-Aufgabe in der Tabelle alma.wf_config';
comment on column alma.wf_link.link_no is 'Reihenfolge der Auswertung';
comment on column alma.wf_link.condition is 'Bedingung ob diese Verzweigung genommen wird oder nicht';


create table alma.wf_step (
    task_id integer references alma.wf_config(wf_config_id) on delete cascade,
    step_id integer references alma.wf_config(wf_config_id) on delete cascade,
    step_no integer not null default 1,
    condition jsonb,
    constraint uq_wf_step_task_id_step_no unique (task_id, step_no),
    constraint pk_wf_step_task_id_step_id primary key (task_id, step_id)
);

comment on table alma.wf_step is 'Teilschritte von Aufgaben';

comment on column alma.wf_step.task_id is 'Id der Aufgabe in der Tabelle alma.wf_config';
comment on column alma.wf_step.step_id is 'Id des Teilschritts (Formular oder Dokument) in der Tabelle alma.wf_config';
comment on column alma.wf_step.step_no is 'Reihenfolge des Schritts innerhalb der Aufgabe';
comment on column alma.wf_step.condition is 'Bedingung ob der Schritt ausgeführt wird oder nicht';


create table alma.wf_node (
    wf_node_id integer not null generated by default as identity,
    title text not null,
    "type" varchar(100) not null,
    wf_config_id integer references alma.wf_config(wf_config_id),
    version integer,
    parent_id integer references alma.wf_node(wf_node_id),
    next_node_id integer references alma.wf_node(wf_node_id),
    is_moveable boolean not null default false,
    status text not null default 'started',
    started_at timestamp without time zone not null default now(),
    finished_at timestamp without time zone,
    deadline timestamp without time zone,
    entity_id integer not null references alma.vflz(vflz_id),
    data jsonb not null default '{}'::jsonb,
    note text,
    form_config jsonb,
    form_data jsonb,
    document_ref varchar(255),
    is_public boolean default false,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    constraint check_status check (status in ('started', 'finished', 'skipped', 'inactive')),
    constraint pk_wf_node_wf_node_id primary key (wf_node_id),
    constraint check_type check ("type" in ('workflow', 'task', 'form', 'document', 'note')),
    constraint check_workflow_version check ((wf_config_id is null and version is null) or (wf_config_id is not null and version is not null)),
    constraint check_deadline_status check ((status = 'inactive' and deadline is null) or (status != 'inactive')),
    -- next_node_id can only be not null if wf_config_id is not null.
    constraint check_next_node_id check ((wf_config_id is null and next_node_id is null) or wf_config_id is not null)
);

comment on table alma.wf_node is 'Laufende Geschäfte (Tasks)';

comment on column alma.wf_node.wf_node_id is 'Primary key';
comment on column alma.wf_node.title is 'Titel Prozess/Aufgabe/Formular/Dokument, etc.';
comment on column alma.wf_node."type" is 'Typ des Tasks: workflow/task/form/document/note';
comment on column alma.wf_node.wf_config_id is 'ID der Konfiguration des Tasks aus der Tabelle alma.wf_config';
comment on column alma.wf_node.version is 'Version der Konfiguration des Tasks aus der Tabelle alma.wf_config';
comment on column alma.wf_node.parent_id is 'Zur hierarchischen Gruppierung von Tasks untereinander';
comment on column alma.wf_node.next_node_id is 'Enthält die ID des nächsten Tasks innerhalb des Prozesses, sobald dieser gestartet wurde.';
comment on column alma.wf_node.is_moveable is 'Gibt an ob der Task in der Hierarchie nachträglich verschoben werden kann';
comment on column alma.wf_node.status is 'Status des tasks (1: gestartet, 2: abgeschlossen, 3: übersprungen, 4: ruhend)';
comment on column alma.wf_node.started_at is 'Start-Datum';
comment on column alma.wf_node.finished_at is 'End-Datum';
comment on column alma.wf_node.deadline is 'Datum Fälligkeit';
comment on column alma.wf_node.entity_id is 'Standortversion';
comment on column alma.wf_node.data is 'Gesammelte Daten aller Prozesschritte bis zu diesem';
comment on column alma.wf_node.note is 'Notiz (freitext)';
comment on column alma.wf_node.form_config is 'Formular-Definition';
comment on column alma.wf_node.form_data is 'Formulareingaben';
comment on column alma.wf_node.document_ref is 'Dokument-Referenz';
comment on column alma.wf_node.is_public is 'Gibt an ob oeffenltich oder nicht';
comment on column alma.wf_node.erfassungs_datum is 'Erfassungs-Datum';
comment on column alma.wf_node.erfasser is 'Erfasser';
comment on column alma.wf_node.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.wf_node.mutierer is 'Bearbeiter der letzten Aenderung';


create table alma.bet_task (
    bet_task_id integer not null generated by default as identity,
    subj_id integer not null references alma.subj(subj_id),
    wf_node_id integer not null references alma.wf_node(wf_node_id),
    vfl_id integer not null,
    h_bez_art integer not null default 2203,
    c_bez_art text not null,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text
);
comment on table alma.bet_task is 'Verknüpfung von Beteiligten mit Tasks';
comment on column alma.bet_task.bet_task_id is 'Primary key';
comment on column alma.bet_task.subj_id is 'Foreign Key: Subjekt';
comment on column alma.bet_task.wf_node_id is 'Foreign Key: Task';
comment on column alma.bet_task.vfl_id is 'Vfl-id des Standorts';
comment on column alma.bet_task.h_bez_art is 'Codeliste für Art des Beteiligten.';
comment on column alma.bet_task.c_bez_art is 'Code für Art des Beteiligten.';
comment on column alma.bet_task.erfassungs_datum is 'Erfassungs-Datum';
comment on column alma.bet_task.erfasser is 'Erfasser';
comment on column alma.bet_task.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.bet_task.mutierer is 'Bearbeiter der letzten Aenderung';


create table alma.task_category (
    task_category_id integer not null generated by default as identity,
    wf_node_id integer not null,
    h_category integer default 10022,
    c_category text,
    constraint pk_task_category_task_category_id primary key (task_category_id),
    constraint fk_wf_node_task_category_wf_node_id foreign key (wf_node_id) references alma.wf_node on update cascade on delete cascade,
    constraint uq_wf_node_category unique (wf_node_id)
);
comment on table alma.task_category is 'Kategorien von Tasks';

comment on column alma.task_category.task_category_id is 'Primary Key';
comment on column alma.task_category.wf_node_id is 'Foreign key: Task';
comment on column alma.task_category.h_category is 'Codeliste Kategorie';
comment on column alma.task_category.c_category is 'Code Kategorie';
