create table alma_admin.search (
    search_id integer not null generated by default as identity,
    is_temporary boolean not null default false,
    name text not null,
    user_id integer not null,
    is_shared boolean not null default false,
    query jsonb not null,
    fields jsonb not null,
    sort_by jsonb not null,
    is_grouped boolean not null,
    constraint pk_search_search_id primary key (search_id),
    constraint fk_auth_user_search_user_id foreign key(user_id) references alma_admin.auth_user(id) on delete cascade,
    constraint uq_search_user_id_search_name unique (user_id, name),
    constraint chk_search_is_temporary_is_shared check ((is_temporary is true and is_shared is not true) or (is_temporary is false))
);

comment on table alma_admin.search is 'Gespeicherte und exportierte Suchen.';

comment on column alma_admin.search.search_id is 'Primary Key';
comment on column alma_admin.search.is_temporary is 'Temporaere Suche fuer Export';
comment on column alma_admin.search.name is 'Name der Suche';
comment on column alma_admin.search.user_id is 'Erfasser';
comment on column alma_admin.search.is_shared is 'Gibt an ob Suche geteilt wird oder nicht';
comment on column alma_admin.search.query is 'Suchabfrage';
comment on column alma_admin.search.fields is 'Ausgabefelder der Suche';
comment on column alma_admin.search.is_grouped is 'Gibt an ob Suchergebnisse gruppiert werden sollen.';

create index ix_pk_search_search_id on alma_admin.search using btree(search_id);
