create table alma_export.search_export (
    search_export_id integer not null generated by default as identity,
    export_id text not null,
    search_id integer not null,
    user_id integer not null,
    format text not null,
    lang text not null,
    path text,
    started_at timestamptz not null default current_timestamp,
    finished_at timestamptz,
    status text not null default 'started',
    constraint pk_search_export_search_export_id primary key (search_export_id),
    constraint fk_search_search_export_search_id foreign key (search_id) references alma_admin.search(search_id) on delete cascade,
    constraint fk_auth_user_search_export_user_id foreign key (user_id) references alma_admin.auth_user(id) on delete cascade,
    constraint uq_export_id unique (export_id),
    constraint ck_status check (status in ('started', 'running', 'success', 'error'))
);

comment on table alma_export.search_export is 'Export einer gespeicherten Suche.';

comment on column alma_export.search_export.search_export_id is 'Primary Key';
comment on column alma_export.search_export.export_id is 'Externe ID';
comment on column alma_export.search_export.search_id is 'ID der gespeicherten Suche';
comment on column alma_export.search_export.user_id is 'Besitzer des Exports';
comment on column alma_export.search_export.format is 'Export-Format';
comment on column alma_export.search_export.lang is 'Export-Sprache';
comment on column alma_export.search_export.path is 'Pfad zur Ausgabedatei';
comment on column alma_export.search_export.started_at is 'Startdatum';
comment on column alma_export.search_export.finished_at is 'Enddatum';
comment on column alma_export.search_export.status is 'Status des Exports';
