create table alma_admin.task_status (
    task_status_id integer not null generated by default as identity,
    name text not null,
    category text not null,
    last_update timestamptz,
    status text not null,
    detail text,
    constraint ck_category check (category in ('import', 'export', 'application')),
    constraint ck_status check (status in ('ok', 'error', 'warning')),
    constraint uq_name unique (name)
);

comment on table alma_admin.task_status is 'Ablage der Status-Infos';

comment on column alma_admin.task_status.task_status_id is 'Primary Key';
comment on column alma_admin.task_status.name is 'Name (unique)';
comment on column alma_admin.task_status.category is 'Kategorie (Import/Export)';
comment on column alma_admin.task_status.last_update is 'Zeitstempel für das letzte Statusupdate';
comment on column alma_admin.task_status.status is 'Taskstatus (ok/error/warning)';
comment on column alma_admin.task_status.detail is 'Detailinformationen';




