create table alma.obje (
    obje_id integer not null generated by default as identity,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone default now(),
    mutierer text,
    constraint pk_obje_obje_id primary key (obje_id)
);

comment on table alma.obje is 'Liste der initalen Standorte. Eine Zuordnung von Teilflaechen zum initalen Standort ist ueber die obje_id moeglich.';

comment on column alma.obje.obje_id IS 'primary key; Zugehoerigkeit initaler Standort obje_id = vflz_id des initalen Standorts';
comment on column alma.obje.erfassungs_datum is 'Erfassungs-Datum';
comment on column alma.obje.erfasser is 'Erfasser';
comment on column alma.obje.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.obje.mutierer is 'Bearbeiter der letzten Aenderung';


create table alma.vflz (
    vflz_id integer not null generated by default as identity,
    vfl_id integer not null,
    obje_id integer not null,
    vflz_laufnr integer default 1 not null,
    vflz_combined_id_kt character varying(50) not null,
    bezeichnung character varying,
    h_vflz_vftyp integer default 63 not null,
    c_vflz_vftyp character varying(8) not null,
    vflz_flurname character varying(100),
    vflz_strasse character varying(100),
    vflz_postleitzahl character varying(8),
    vflz_ort character varying(100),
    h_gem_id integer,
    zentroid public.geometry(POINTZ, 2056) not null,
    h_org_kuerzel integer not null,
    c_org_kuerzel character varying(8) not null,
    zeitraum_bis date,
    zeitraum_von date,
    zeitraum_bisheute boolean default false not null,
    zeitraum_bisjahr boolean default false,
    zeitraum_vonjahr boolean default false,
    flugplatz text,
    h_vflz_deponietyp integer default 12001,
    c_vflz_deponietyp character varying(8),
    in_betrieb boolean,
    nachsorge boolean,
    h_vflz_gws_bereich integer default 10017,
    c_vflz_gws_bereich character varying(8),
    h_vflz_gws_zone integer default 10018,
    c_vflz_gws_zone character varying(8) default null::character varying,
    h_vflz_durchlaessigkeit integer default 58,
    c_vflz_durchlaessigkeit character varying(8),
    h_vflz_karstgeb integer default 80,
    c_vflz_karstgeb character varying(8),
    h_vflz_bearbstand integer default 55,
    c_vflz_bearbstand character varying(20),
    h_vflz_unterstand integer default 10023,
    c_vflz_unterstand character varying(20),
    rechtskraft boolean default false,
    publizieren boolean default false,
    dat_rechtskraft date,
    dat_publizieren date,
    lang character varying default 'de'::character varying not null,
    is_current boolean not null default true,
    message text not null,
    parent_id integer,
    vflz_created_date timestamp without time zone default now(),
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    constraint pk_vflz_vflz_id primary key (vflz_id),   
    constraint fk_obje_vflz_obje_id foreign key (obje_id) references alma.obje(obje_id) on update cascade on delete cascade,
    constraint fk_vflz_vflz_parent_id foreign key (parent_id) references alma.vflz(vflz_id) on delete set null,
    constraint ex_vflz_vfl_id_is_current_true exclude (vfl_id with =) where (is_current = true) deferrable initially deferred , -- Ensure that there is at most one current entry per vfl_id
    constraint chk_vflz_h_vflz_vftyp check ((h_vflz_vftyp = 63))
);

comment on table alma.vflz is 'vflz enthaelt die applikations-spezifischen Daten des KbS. vflz steht fuer VerdachtsFLaechen-Zustand. vflz bietet die Moeglichkeit, verschiedene Zustaende von Standorten zu erfassen. Daneben enthaelt vflz Adressdaten, verschiedenste technische Daten und Daten zum Untergrund. Ein Datensatz in vflz hat immer genau einen Standorttyp.';

comment on column alma.vflz.vflz_id is 'primary key; Verdachtsflaechenzahl';
comment on column alma.vflz.vfl_id is 'foreign_key; Zusammengehoerigkeit von Standortversionen';
comment on column alma.vflz.obje_id is 'foreign key; Zusammengehoerigkeit von Teilflaechen';
comment on column alma.vflz.vflz_laufnr is 'Laufnummer fuer die historisierten Standortversionen';
comment on column alma.vflz.vflz_combined_id_kt is 'Standortnummer';
comment on column alma.vflz.bezeichnung is 'Bezeichnung des Standortes, Standortname';
comment on column alma.vflz.h_vflz_vftyp is 'Codeliste Verdachtsflaechentyp';
comment on column alma.vflz.c_vflz_vftyp is 'Code Verdachtsflaechentyp: 01-Ablagerung, 02-Betrieb, 03-Unfall, 04-Schiessanlage';
comment on column alma.vflz.vflz_flurname is 'Flurname';
comment on column alma.vflz.vflz_strasse is 'Strasse und Hausnummer';
comment on column alma.vflz.vflz_postleitzahl is 'Postleitzahl';
comment on column alma.vflz.vflz_ort is 'Ort, entsprechend einem PLZ-Bezirk.';
comment on column alma.vflz.h_gem_id is 'BfS-Gemeindenummer';
comment on column alma.vflz.zentroid is 'Zentroid Koordinaten des Standorts';
comment on column alma.vflz.h_org_kuerzel is 'Codeliste Kuerzel zum zustaendigen Amt.';
comment on column alma.vflz.c_org_kuerzel is 'Kuerzel zum zustaendigem Amt';
comment on column alma.vflz.zeitraum_bis is 'Startzeitpunkt der Nutzung - automatische Generierung aus den Daten zu Ablagerungen, Betrieben, Unfaellen oder Schiessanlagen';
comment on column alma.vflz.zeitraum_von is 'Endzeitpunkt der Nutzung - automatische Generierung aus den Daten zu Ablagerungen, Betrieben, Unfaellen oder Schiessanlagen';
comment on column alma.vflz.zeitraum_bisheute is 'Entzeitpunkt vorhanden - automatische Generierung aus den Daten zu Ablagerungen, Betrieben, Unfaellen oder Schiessanlagen';
comment on column alma.vflz.zeitraum_bisjahr is 'Startzeitpunkt als Jahr angegeben - automatische Generierung aus den Daten zu Ablagerungen, Betrieben, Unfaellen oder Schiessanlagen';
comment on column alma.vflz.zeitraum_vonjahr is 'Endzeitpunkt als Jahr angegeben -automatische Generierung aus den Daten zu Ablagerungen, Betrieben, Unfaellen oder Schiessanlagen';
comment on column alma.vflz.flugplatz is 'foreigen_key; alma.h_flugplatz.icao; Kuerzel Flugplatz';
comment on column alma.vflz.h_vflz_deponietyp is 'Codeliste Deponietyp';
comment on column alma.vflz.c_vflz_deponietyp is 'Typ-Code Deponietyp';
comment on column alma.vflz.in_betrieb is 'Gibt an ob Standort in Betrieb ist';
comment on column alma.vflz.nachsorge is 'Gibt an ob eine Nachsorge notwendig ist';
comment on column alma.vflz.h_vflz_gws_bereich is 'Codeliste Gewaesserschutzbereich (natuerl. Umfeld)';
comment on column alma.vflz.c_vflz_gws_bereich is 'Code Gewaesserschutzbereich (natuerl. Umfeld)';
comment on column alma.vflz.h_vflz_gws_zone is 'Codeliste Grundwasserschutzzone';
comment on column alma.vflz.c_vflz_gws_zone is 'Code Grundwasserschutzzone';
comment on column alma.vflz.h_vflz_durchlaessigkeit is 'Codeliste Durchlaessigkeit Untergrund (natuerl. Umfeld)';
comment on column alma.vflz.c_vflz_durchlaessigkeit is 'Code Durchlaessigkeit Untergrund (natuerl. Umfeld)';
comment on column alma.vflz.h_vflz_karstgeb is 'Codeliste Karstgebiet (natuerl. Umfeld)';
comment on column alma.vflz.c_vflz_karstgeb is 'Code Karstgebiet (natuerl. Umfeld)';
comment on column alma.vflz.h_vflz_bearbstand is 'Codeliste Bearbeitungsstand';
comment on column alma.vflz.c_vflz_bearbstand is 'Code Bearbeitungsstand - abhängig von Prozessen';
comment on column alma.vflz.h_vflz_unterstand is 'Codeliste Untersuchungsstand';
comment on column alma.vflz.c_vflz_unterstand is 'Code Untersuchungsstand - abhängig von Prozessen';
comment on column alma.vflz.rechtskraft is 'Zustand der Rechtsgültigkeit - abhängig von Prozessen';
comment on column alma.vflz.publizieren is 'Zustand der Publikation im Kataster belasteter Standorte - abhängig von Prozessen';
comment on column alma.vflz.dat_rechtskraft is 'Datum der Rechtsgültigket - abhängig von Prozessen';
comment on column alma.vflz.dat_publizieren is 'Datum der Publikation - abhängig von Prozessen';
comment on column alma.vflz.lang is 'Sprachauswahl die Standardeinstellung in den Reporten - Abhängig von der geographischen Lage';
comment on column alma.vflz.is_current is 'Aktuelle oder historisierte Version';
comment on column alma.vflz.message is 'Grund der Historisierung';
comment on column alma.vflz.parent_id is 'Foreign key: Vorherige Version';
comment on column alma.vflz.vflz_created_date is 'Datum der Versionserstellung';
comment on column alma.vflz.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.vflz.erfasser is 'Erfasser';
comment on column alma.vflz.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.vflz.mutierer is 'Bearbeiter der letzten Aenderung';

create index fki_vflz_vflz_vftyp on alma.vflz using btree (h_vflz_vftyp, c_vflz_vftyp);
create index idx_vflz_app_obje_id on alma.vflz using btree (obje_id);
create index idx_vflz_bezeichnung on alma.vflz using btree (bezeichnung);
create index idx_vflz_vfl_id on alma.vflz using btree (vfl_id);
create index idx_vflz_vflz_combined_id_kt on alma.vflz using btree (vflz_combined_id_kt);
create index ix_fk_app_obje_vflz_app_obje_id on alma.vflz using btree (obje_id);


create table alma.vflnr (
    vflnr_id integer not null generated by default as identity,
    vflz_id integer not null,
    h_org_kuerzel integer not null,
    c_org_kuerzel text not null,
    aktiv boolean not null default false,
    nummer text not null,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint pk_vflnr_vflnr_id primary key (vflnr_id),
    constraint uq_vflz_id_c_org_kuerzel unique (vflz_id, c_org_kuerzel) deferrable initially deferred,
    constraint ex_vflnr_vflz_id_aktiv_true exclude (vflz_id with =) where (aktiv = true) deferrable initially deferred,
    constraint fk_vflnr_vflz_id foreign key (vflz_id) references alma.vflz(vflz_id) on delete cascade on update cascade
);

comment on table alma.vflnr is 'Relevante Daten zum Vollzug des Vflzs';
comment on column alma.vflnr.vflnr_id is 'Primary key';
comment on column alma.vflnr.vflz_id is 'Foreign Key auf VFLZ.';
comment on column alma.vflnr.h_org_kuerzel is 'Codeliste Behoerdenkuerzel.';
comment on column alma.vflnr.c_org_kuerzel is 'Code Behoerdenkuerzel.';
comment on column alma.vflnr.aktiv is 'Gibt an ob diese Behoerde im Vollzug ist.';
comment on column alma.vflnr.nummer is 'Standortnummer';
comment on column alma.vflnr.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.vflnr.erfasser is 'Erfasser';
comment on column alma.vflnr.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.vflnr.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.vflnr.is_current is 'Aktuelle oder historisierte Version';
