create table documents.asset (
    asset_id integer not null generated by default as identity,
    uuid uuid not null,
    file_path text not null,
    file_size integer,
    file_type text not null,
    original_file_name text not null,
    preview_path text,
    title text not null,
    constraint pk_asset_asset_id primary key (asset_id),
    constraint uq_asset_uuid unique (uuid)
);

comment on table documents.asset is 'Dokumenten-spezifische Daten wie Dateipfad, etc.';

comment on column documents.asset.asset_id is 'Primary key';
comment on column documents.asset.uuid is 'UUID';
comment on column documents.asset.file_path is 'Dateipfad';
comment on column documents.asset.file_size is 'Dateigroesse';
comment on column documents.asset.file_type is 'Dateityp';
comment on column documents.asset.preview_path is 'Optionaler Pfad zum Preview';
comment on column documents.asset.original_file_name is 'Original Dateiname';
comment on column documents.asset.title is 'Optionale Dokumentenbezeichnung';

create index ix_pk_asset_asset_id on documents.asset using btree(asset_id);



