create table alma.flugplatz (
    flugplatz_id integer not null generated by default as identity,
    art text not null,
    h_flugplatz_bezeichnung integer not null default 600,
    c_flugplatz_bezeichnung text not null,
    icao text not null,
    abk text not null,
    c_kt text not null,
    zusatz text not null,
    wkb_geometry public.geometry not null,
    constraint pk_flugplatz_flugplatz_id primary key (flugplatz_id),
    constraint enforce_dims_wkb_geometry check ((public.st_ndims(wkb_geometry) = 2)),
    constraint enforce_srid_wkb_geometry check ((public.st_srid(wkb_geometry) = 2056)),
    constraint enforce_geometry_type_wkb_geometry check ((public.st_geometrytype(wkb_geometry) = any (array['ST_MultiPolygon'::text, 'ST_Point'::text]))),
    constraint uq_c_flugplatz_bezeichnung unique (c_flugplatz_bezeichnung),
    constraint uq_icao unique (icao)
);

comment on table alma.flugplatz is 'Tabelle der Flugplätze';

comment on column alma.flugplatz.flugplatz_id IS 'primary key';
comment on column alma.flugplatz.art IS 'Art des Flugplatzes';
comment on column alma.flugplatz.h_flugplatz_bezeichnung IS 'Codeliste Flugplatz-Bezeichnung';
comment on column alma.flugplatz.c_flugplatz_bezeichnung IS 'Code für Flugplatz-Bezeichnung';
comment on column alma.flugplatz.icao IS 'ICAO-Code des Flugplatzes';
comment on column alma.flugplatz.abk IS 'Abkürzung des Flugplatzes';
comment on column alma.flugplatz.c_kt IS 'Kennung des Flugplatzes';
comment on column alma.flugplatz.zusatz IS 'Zusatzinformationen zum Flugplatz';
comment on column alma.flugplatz.wkb_geometry IS 'Geometrie';


alter table alma.vflz add column flugplatz_id integer;
alter table alma.vflz add constraint fk_flugplatz_vflz_flugplatz_id foreign key (flugplatz_id) references alma.flugplatz (flugplatz_id) on update cascade on delete set null;
alter table alma.vflz drop column flugplatz;

comment on column alma.vflz.flugplatz_id is 'Fremdschlüssel auf Flugplatz';
