create table alma.event (
    event_id integer generated by default as identity,
    event_type varchar(200) not null,
    event_data jsonb not null,
    event_timestamp timestamptz not null,
    vflz_id integer not null,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone default now(),
    mutierer text,
    constraint pk_event_event_id primary key (event_id)
);

comment on table alma.event is 'Ereignisse (Events)';
comment on column alma.event.event_id is 'Primary key';
comment on column alma.event.event_type is 'Typ des Events';
comment on column alma.event.event_data is 'Daten des Events';
comment on column alma.event.event_timestamp is 'Zeitpunkt des Events';
comment on column alma.event.vflz_id is 'ID des Standorts bei dessen Geschäft das Event ausgelöst wurde.';
comment on column alma.event.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.event.erfasser is 'Erfasser';
comment on column alma.event.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.event.mutierer is 'Bearbeiter der letzten Aenderung';


alter table alma.wf_config rename column events to triggers;


create table alma.wf_node_event (
    wf_node_id integer not null references alma.wf_node (wf_node_id),
    event_id integer not null references alma.event (event_id),
    constraint pk_wf_node_event_wf_node_id_event_id primary key (wf_node_id, event_id)
);

comment on table alma.wf_node_event is 'Ereignisse die durch einen Task ausgelöst wurden';
comment on column alma.wf_node_event.wf_node_id is 'ID des Tasks (node)';
comment on column alma.wf_node_event.event_id is 'ID des Events';


alter table alma.wf_node add column events_triggered boolean not null default false;
comment on column alma.wf_node.events_triggered is 'Wahr, wenn Events für diesen Task bereits ausgelöst wurden';
