create table alma_external.report_export_offset (
    report_export_offset_id integer not null generated by default as identity,
    report_id integer not null,
    last_vflz_id integer not null,
    constraint pk_exports_cache_id primary key (report_export_offset_id),
    constraint uq_report_export_offset_offset unique (report_id)
);

comment on table alma_external.report_export_offset is 'Auxiliary table for caching vflz offsets for report export.';
comment on column alma_external.report_export_offset.report_export_offset_id is 'Primary key';
comment on column alma_external.report_export_offset.report_id is 'Report ID';
comment on column alma_external.report_export_offset.last_vflz_id is 'Last vflz_id the report was created for';
