create table alma.intk (
    intk_id integer not null generated by default as identity,
    vflz_id integer not null,
    name text,
    eva_nummer text,
    strasse text,
    plz text,
    ort text,
    von date,
    bis date,
    zeitraum_bisheute boolean default false not null,
    zeitraum_bisjahr boolean default false not null,
    zeitraum_vonjahr boolean default false not null,
    h_infg_von integer default 90,
    c_infg_von character varying(8),
    h_infg_bis integer default 90,
    c_infg_bis character varying(8),
    h_kinderspielplatz_gruenflache_typ integer default 400,
    c_kinderspielplatz_gruenflache_typ text,
    h_eigentumsform integer default 401,
    c_eigentumsform text,
    belastung_ueber_sanierungswert boolean,
    relevant boolean default false,
    h_untersuchungsstand integer default 10023,
    c_untersuchungsstand character varying(8),
    h_beurteilung integer default 103,
    c_beurteilung character varying(8),
    zentroid public.geometry(POINT, 2056),
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint pk_intk_intk_id primary key (intk_id),
    constraint fk_vflz_intk_vflz_id foreign key (vflz_id) references alma.vflz(vflz_id) on update cascade on delete cascade
);

comment on table alma.intk is 'Standorttyp-spezifische Daten zu Kinderspielplätzen und Grünflächen. Ein Standort kann mehrere intk-Zuweisungen haben.';

comment on column alma.intk.intk_id is 'Primary key';
comment on column alma.intk.vflz_id is 'Foreign key zum Standort';
comment on column alma.intk.name is 'Name des Kinderspielplatzes oder der Grünfläche';
comment on column alma.intk.eva_nummer is 'EVA-Nummer';
comment on column alma.intk.strasse is 'Straße';
comment on column alma.intk.plz is 'Postleitzahl';
comment on column alma.intk.ort is 'Ort';
comment on column alma.intk.von is 'Gültig ab (Datum)';
comment on column alma.intk.bis is 'Gültig bis (Datum)';
comment on column alma.intk.zeitraum_bisheute is '';
comment on column alma.intk.zeitraum_bisjahr is '';
comment on column alma.intk.zeitraum_vonjahr is '';
comment on column alma.intk.h_infg_von is 'Codeliste für "von"-Information';
comment on column alma.intk.c_infg_von is 'Code für "von"-Information';
comment on column alma.intk.h_infg_bis is 'Codeliste für "bis"-Information';
comment on column alma.intk.c_infg_bis is 'Code für "bis"-Information';
comment on column alma.intk.h_kinderspielplatz_gruenflache_typ is 'Codeliste Typ';
comment on column alma.intk.c_kinderspielplatz_gruenflache_typ is 'Code Typ';
comment on column alma.intk.h_eigentumsform is 'Codeliste für Eigentumsform';
comment on column alma.intk.c_eigentumsform is 'Code Eigentumsform';
comment on column alma.intk.belastung_ueber_sanierungswert is 'Belastung über Sanierungswert (true/false)';
comment on column alma.intk.relevant is 'Kasterrelevanz (true/false)';
comment on column alma.intk.h_untersuchungsstand is 'Codeliste für Untersuchungsstand';
comment on column alma.intk.c_untersuchungsstand is 'Code Untersuchungsstand';
comment on column alma.intk.h_beurteilung is 'Codeliste für Beurteilung';
comment on column alma.intk.c_beurteilung is 'Code Beurteilung';
comment on column alma.intk.zentroid is 'Zentroid (Punkt, EPSG:2056)';
comment on column alma.intk.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.intk.erfasser is 'Erfasser';
comment on column alma.intk.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.intk.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.intk.is_current is 'Aktuelle oder historisierte Version';


create table alma.intk_altersstufe (
    intk_altersstufe_id integer not null generated by default as identity,
    intk_id integer not null,
    h_altersstufe_kinder integer default 402,
    c_altersstufe_kinder text not null,
    constraint pk_intk_altersstufe primary key (intk_altersstufe_id),
    constraint fk_intk_altersstufe_intk_id foreign key (intk_id) references alma.intk(intk_id) on update cascade on delete cascade,
    constraint uq_intk_altersstufe unique (intk_id, c_altersstufe_kinder)
);

comment on table alma.intk_altersstufe is 'Altersstufen für Kinderspielplätze/Grünflächen. Ein Kinderspielplatz/Grünfläche kann mehrere Altersstufen haben.';

comment on column alma.intk_altersstufe.intk_altersstufe_id is 'Primary key';
comment on column alma.intk_altersstufe.intk_id is 'Foreign key';
comment on column alma.intk_altersstufe.h_altersstufe_kinder is 'Codeliste für Altersstufe Kinder';
comment on column alma.intk_altersstufe.c_altersstufe_kinder is 'Code Altersstufe Kinder';
