create table alma.ktu (
    ktu_id integer generated by default as identity,
    h_ktu integer not null default 110,
    c_ktu text not null,
    rangefrom integer not null,
    rangeto integer not null,
    constraint pk_ktu_ktu_id primary key (ktu_id),
    constraint uq_ktu_c_ktu unique (ktu_id, c_ktu)
);

comment on table alma.ktu is 'Konzessionierte Transportunternehmen';

comment on column alma.ktu.ktu_id is 'Primary key';
comment on column alma.ktu.h_ktu is 'Codeliste KTU';
comment on column alma.ktu.c_ktu is 'Code KTU';
comment on column alma.ktu.rangefrom is 'Bereich für Standortnummergenerierung, von';
comment on column alma.ktu.rangeto is 'Bereich für Standortnummergenerierung, bis';

alter table alma.vflz add column ktu_id integer;
alter table alma.vflz add constraint fk_vflz_ktu_id foreign key (ktu_id) references alma.ktu (ktu_id) on delete set null;

comment on column alma.vflz.ktu_id is 'Foreign key to alma.ktu.ktu_id';
