create table alma.intp (
    intp_id integer not null generated by default as identity,
    vflz_id integer not null,
    name text,
    strasse text,
    plz text,
    ort text,
    eva_nummer text,
    von date,
    bis date,
    zeitraum_bisheute boolean default false not null,
    zeitraum_bisjahr boolean default false not null,
    zeitraum_vonjahr boolean default false not null,
    h_infg_von integer default 90,
    c_infg_von character varying(8),
    h_infg_bis integer default 90,
    c_infg_bis character varying(8),
    h_pfas_typ integer default 500,
    c_pfas_typ character varying(8),
    pfas_loeschmittel boolean default false,
    menge_schaumgemisch integer,
    menge_konzentrat integer,
    beschreibungen_detail text,
    relevant boolean,
    h_untersuchungsstand integer default 10023,
    c_untersuchungsstand character varying(8),
    h_beurteilung integer default 103,
    c_beurteilung character varying(8),
    h_branche integer default 25002,
    c_branche character varying(8),
    zentroid public.geometry(POINT, 2056),
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint pk_intp_intp_id primary key (intp_id),
    constraint fk_vflz_intp_vflz_id foreign key (vflz_id) references alma.vflz (vflz_id) on update cascade on delete cascade
);

comment on table alma.intp is 'PFAS-Feuerlösch-Standorte';

comment on column alma.intp.intp_id is 'Eindeutige ID des PFAS-Feuerlösch-Standorts';
comment on column alma.intp.vflz_id is 'Verweis auf den zugehörigen VFLZ-Eintrag';
comment on column alma.intp.name is 'Name des PFAS-Feuerlösch-Standorts';
comment on column alma.intp.strasse is 'Straße des PFAS-Feuerlösch-Standorts';
comment on column alma.intp.plz is 'Postleitzahl des PFAS-Feuerlösch-Standorts';
comment on column alma.intp.ort is 'Ort des PFAS-Feuerlösch-Standorts';
comment on column alma.intp.eva_nummer is 'EVA-Nummer des PFAS-Feuerlösch-Standorts';
comment on column alma.intp.von is 'Datum des Beginns der Tätigkeit am PFAS-Feuerlösch-Standort';
comment on column alma.intp.bis is 'Datum des Endes der Tätigkeit am PFAS-Feuerlösch-Standort';
comment on column alma.intp.zeitraum_bisheute is 'Gibt an, ob der Zeitraum bis heute andauert';
comment on column alma.intp.zeitraum_bisjahr is 'Gibt an, ob nur das Endjahr des Zeitraums bekannt ist';
comment on column alma.intp.zeitraum_vonjahr is 'Gibt an, ob nur das Startjahr des Zeitraums bekannt ist';
comment on column alma.intp.h_infg_von is 'Genauigkeit des von-Datums';
comment on column alma.intp.c_infg_von is 'Code für die Genauigkeit des von-Datums';
comment on column alma.intp.h_infg_bis is 'Genauigkeit des bis-Datums';
comment on column alma.intp.c_infg_bis is 'Code für die Genauigkeit des bis-Datums';
comment on column alma.intp.h_pfas_typ is 'Codeliste PFAS-Typ';
comment on column alma.intp.c_pfas_typ is 'Code PFAS-Typ';
comment on column alma.intp.pfas_loeschmittel is 'Gibt an, ob PFAS-haltiges Löschmittel verwendet wurde';
comment on column alma.intp.menge_schaumgemisch is 'Menge des eingesetzten Schaumgemischs in m3';
comment on column alma.intp.menge_konzentrat is 'Menge des eingesetzten Konzentrats in Litern';
comment on column alma.intp.beschreibungen_detail is 'Detaillierte Beschreibung des PFAS-Feuerlösch-Standorts';
comment on column alma.intp.relevant is 'Gibt an, ob der PFAS-Feuerlösch-Standort katasterrelevant ist';
comment on column alma.intp.h_untersuchungsstand is 'Genauigkeit des Untersuchungsstands';
comment on column alma.intp.c_untersuchungsstand is 'Code für die Genauigkeit des Untersuchungsstands';
comment on column alma.intp.h_beurteilung is 'ASW-Code für die Branche';
comment on column alma.intp.c_beurteilung is 'Branche';
comment on column alma.intp.h_branche is 'Genauigkeit der Branche';
comment on column alma.intp.c_branche is 'Code für die Genauigkeit der Branche';
comment on column alma.intp.zentroid is 'Geometrisches Zentrum des PFAS-Feuerlösch-Standorts';
comment on column alma.intp.erfassungs_datum is 'Datum der Erfassung des PFAS-Feuerlösch-Standorts';
comment on column alma.intp.erfasser is 'Erfasser des PFAS-Feuerlösch-Standorts';
comment on column alma.intp.mutations_datum is 'Datum der letzten Mutation des PFAS-Feuerlösch-Standorts';
comment on column alma.intp.mutierer is 'Mutierer des PFAS-Feuerlösch-Standorts';
comment on column alma.intp.is_current is 'Gibt an, ob der PFAS-Feuerlösch-Standort aktuell ist';


create table alma.intp_pfas_haltige_loeschmittel (
    intp_pfas_haltige_loeschmittel_id integer not null generated by default as identity,
    intp_id integer not null,
    h_loeschmittel_pfas_haltig integer default 501,
    c_loeschmittel_pfas_haltig character varying(8),
    constraint pk_intp_pfas_haltige_loeschmittel_intp_pfas_haltige_loeschmittel_id primary key (intp_pfas_haltige_loeschmittel_id),
    constraint fk_intp_intp_pfas_haltige_loeschmittel_intp_id foreign key (intp_id) references alma.intp (intp_id),
    constraint uq_intp_pfas_haltige_loeschmittel unique (intp_id, c_loeschmittel_pfas_haltig)
);

comment on table alma.intp_pfas_haltige_loeschmittel is 'PFAS-haltige Löschmittel am PFAS-Feuerlösch-Standort';

comment on column alma.intp_pfas_haltige_loeschmittel.intp_id is 'Eindeutige ID des PFAS-Feuerlösch-Standorts';
comment on column alma.intp_pfas_haltige_loeschmittel.h_loeschmittel_pfas_haltig is 'Codeliste für PFAS-haltige Löschmittel';
comment on column alma.intp_pfas_haltige_loeschmittel.c_loeschmittel_pfas_haltig is 'Code für PFAS-haltige Löschmittel';


create table alma.intp_pfas_freie_loeschmittel (
    intp_pfas_freie_loeschmittel_id integer not null generated by default as identity,
    intp_id integer not null,
    h_loeschmittel_pfas_frei integer default 502,
    c_loeschmittel_pfas_frei character varying(8),
    constraint pk_intp_pfas_freie_loeschmittel_intp_pfas_freie_loeschmittel_id primary key (intp_pfas_freie_loeschmittel_id),
    constraint fk_intp_intp_pfas_freie_loeschmittel_intp_id foreign key (intp_id) references alma.intp (intp_id),
    constraint uq_intp_pfas_freie_loeschmittel unique (intp_id, c_loeschmittel_pfas_frei)
);

comment on table alma.intp_pfas_freie_loeschmittel is 'PFAS-freie Löschmittel am PFAS-Feuerlösch-Standort';

comment on column alma.intp_pfas_freie_loeschmittel.intp_id is 'Eindeutige ID des PFAS-Feuerlösch-Standorts';
comment on column alma.intp_pfas_freie_loeschmittel.h_loeschmittel_pfas_frei is 'Codeliste für PFAS-freie Löschmittel';
comment on column alma.intp_pfas_freie_loeschmittel.c_loeschmittel_pfas_frei is 'Code für PFAS-freie Löschmittel';


create table alma.intp_loeschschaum_einsatz (
    intp_loeschschaum_einsatz_id integer not null generated by default as identity,
    intp_id integer not null,
    h_loeschschaum_einsatz integer default 503,
    c_loeschschaum_einsatz character varying(8) not null,
    h_haeufigkeit_nutzung integer not null,
    c_haeufigkeit_nutzung character varying(8) not null,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint pk_intp_loeschschaum_einsatz_id primary key (intp_loeschschaum_einsatz_id),
    constraint fk_intp_intp_loeschschaum_einsatz_intp_id foreign key (intp_id) references alma.intp (intp_id),
    constraint uq_intp_loeschschaum_einsatz unique (intp_id, c_loeschschaum_einsatz)
);

comment on table alma.intp_loeschschaum_einsatz is 'Mapping von Löschschaum-Einsatz zu PFAS-Feuerlösch-Standorten';

comment on column alma.intp_loeschschaum_einsatz.intp_loeschschaum_einsatz_id is 'Eindeutige ID des Mapping-Eintrags';
comment on column alma.intp_loeschschaum_einsatz.intp_id is 'Verweis auf den zugehörigen PFAS-Feuerlösch-Standort';
comment on column alma.intp_loeschschaum_einsatz.h_loeschschaum_einsatz is 'Codeliste Löschschaum-Einsatz';
comment on column alma.intp_loeschschaum_einsatz.c_loeschschaum_einsatz is 'Code Löschschaum-Einsatz';
comment on column alma.intp_loeschschaum_einsatz.h_haeufigkeit_nutzung is 'Codeliste Häufigkeit der Nutzung (abh. von der c_loeschschaum_einsatz)';
comment on column alma.intp_loeschschaum_einsatz.c_haeufigkeit_nutzung is 'Code Häufigkeit der Nutzung';
comment on column alma.intp_loeschschaum_einsatz.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.intp_loeschschaum_einsatz.erfasser is 'Erfasser';
comment on column alma.intp_loeschschaum_einsatz.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.intp_loeschschaum_einsatz.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.intp_loeschschaum_einsatz.is_current is 'Aktuelle oder historisierte Version';
