create table alma_export.jahrestrends (
    id integer not null generated by default as identity,
    jahr integer,
    anzahl integer,
    label text, 
    kategorie text,
    constraint pk_jahrestrends_id primary key (id)
);

comment on table alma_export.jahrestrends is 'Tabelle für die Jahres-Trends';

comment on column alma_export.jahrestrends.jahr is 'Jahr der Erhebung';
comment on column alma_export.jahrestrends.anzahl is 'Anzahl der Einträge im jeweiligen Jahr';
comment on column alma_export.jahrestrends.label is 'Bezeichnung';
comment on column alma_export.jahrestrends.kategorie is 'Kategorie';
