create table alma.inta (
    inta_id integer not null generated by default as identity,
    vflz_id integer not null,
    inta_vol_kompartiment double precision,
    inta_ablag_von date,
    inta_ablag_bis date,
    zeitraum_bisheute boolean default false not null,
    zeitraum_bisjahr boolean default false not null,
    zeitraum_vonjahr boolean default false not null,
    inta_tiefe text,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint pk_inta_inta_id primary key (inta_id),
    constraint fk_vflz_inta_vflz_id foreign key (vflz_id) references alma.vflz(vflz_id) on update cascade on delete cascade
);

comment on table alma.inta is 'Standorttyp-spezifische Daten zu Ablagerungen. Mehrere Datensaetze in inta zu einem Standort beschreiben verschiedene Kompartimente von Ablagerungen.';

comment on column alma.inta.inta_id is 'primary key';
comment on column alma.inta.vflz_id is 'foreign key; alma.vflz';
comment on column alma.inta.inta_vol_kompartiment is 'Volumen des Kompartiments [m3]';
comment on column alma.inta.inta_ablag_von is 'Beginn der Ablagerung im Kompartiment';
comment on column alma.inta.inta_ablag_bis is 'Ende der Ablageurng im Kompartiment. Kein Eintrag bedeutet in der Regel, dass die Ablagerung noch andauert.';
comment on column alma.inta.zeitraum_bisheute is 'Ablagerung aktiv';
comment on column alma.inta.zeitraum_bisjahr is 'Jahr des Ablagerungsbegin';
comment on column alma.inta.zeitraum_vonjahr is 'Jahr des Ablagerungsende';
comment on column alma.inta.inta_tiefe is 'Tiefe der Ablagerung [m2]';
comment on column alma.inta.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.inta.erfasser is 'Erfasser';
comment on column alma.inta.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.inta.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.inta.is_current is 'Aktuelle oder historisierte Version';

create index ix_fk_vflz_inta_vflz_id on alma.inta using btree (vflz_id);



create table alma.kksk (
    kksk_id integer not null generated by default as identity,
    inta_id integer not null,
    kksk_teilvol double precision,
    h_kksk_stoffkl integer default 94,
    c_kksk_stoffkl character varying(8),
    h_kksk_infg_ablag_von integer default 90,
    c_kksk_infg_ablag_von character varying(8),
    h_kksk_infg_ablag_bis integer default 90,
    c_kksk_infg_ablag_bis character varying(8),
    kksk_ablag_von date,
    kksk_ablag_bis date,
    zeitraum_bisheute boolean default false not null,
    zeitraum_bisjahr boolean default false not null,
    zeitraum_vonjahr boolean default false not null,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint pk_kksk_kksk_id primary key (kksk_id),
    constraint fk_inta_kksk_inta_id foreign key (inta_id) references alma.inta(inta_id) on update cascade on delete cascade
);

comment on table alma.kksk is 'Bei Ablagerungsstandorten im Kompartiment eingelagerte Stoffe';

comment on column alma.kksk.kksk_id is 'primary key';
comment on column alma.kksk.inta_id is 'foreign key; alma.inta';
comment on column alma.kksk.kksk_teilvol is 'Teilvolumen der Stoffklasse im Kompartiment';
comment on column alma.kksk.h_kksk_stoffkl is 'Codeliste Stoffklasse';
comment on column alma.kksk.c_kksk_stoffkl is 'Code Stoffklasse';
comment on column alma.kksk.h_kksk_infg_ablag_bis is 'Codeliste Genauigkeit Startzeitpunkt';
comment on column alma.kksk.c_kksk_infg_ablag_bis is 'Code Genauigkeit Startzeitpunkt';
comment on column alma.kksk.h_kksk_infg_ablag_von is 'Codeliste Genauigkeit Endzeitpunkt';
comment on column alma.kksk.c_kksk_infg_ablag_von is 'Code Genauigkeit Endzeitpunkt';
comment on column alma.kksk.kksk_ablag_von is 'Beginn der Ablagerung';
comment on column alma.kksk.kksk_ablag_bis is 'Ende der Ablageurng';
comment on column alma.kksk.zeitraum_bisheute is 'Ablagerung aktiv';
comment on column alma.kksk.zeitraum_bisjahr is 'Jahr des Ablagerungsbegin';
comment on column alma.kksk.zeitraum_vonjahr is 'Jahr des Ablagerungsende';
comment on column alma.kksk.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.kksk.erfasser is 'Erfasser';
comment on column alma.kksk.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.kksk.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.kksk.is_current is 'Aktuelle oder historisierte Version';

CREATE INDEX ix_fk_inta_kksk_inta_id ON alma.kksk USING btree (inta_id);



create table alma.kksg (
    kksg_id integer not null generated by default as identity,
    kksk_id integer not null,
    kksg_teilvol double precision,
    h_kksg_stoffgrp integer default 115,
    c_kksg_stoffgrp character varying(8),
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint pk_kksg_kksg_id primary key (kksg_id),
    constraint fk_kksk_kksg_kksk_id foreign key (kksk_id) references alma.kksk(kksk_id) on update cascade on delete cascade
);

comment on table alma.kksg is 'Stoffgruppen bei Ablagerungsstandorten im Kompartiment und innerhalb der Stoffklassen(kksk)';

comment on column alma.kksg.kksg_id is 'primary key';
comment on column alma.kksg.kksk_id is 'foreign key; alma.kksk';
comment on column alma.kksg.kksg_teilvol is 'Volumen der Stoffgruppe';
comment on column alma.kksg.c_kksg_stoffgrp is 'Codeliste Stoffgruppe, in Abhaengigkeit der Stoffklasse in kksg';
comment on column alma.kksg.c_kksg_stoffgrp is 'Code Stoffgruppe, in Abhaengigkeit der Stoffklasse in kksg';
comment on column alma.kksg.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.kksg.erfasser is 'Erfasser';
comment on column alma.kksg.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.kksg.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.kksg.is_current is 'Aktuelle oder historisierte Version';

create index ix_fk_kksk_kksg_kksk_id on alma.kksg using btree (kksk_id);



create table alma.intb (
    intb_id integer not null generated by default as identity,
    vflz_id integer not null,
    intb_typ character varying(8) not null,
    intb_firma_name character varying,
    intb_firma_strasse character varying,
    intb_firma_plz character varying(8),
    intb_firma_ort character varying,
    intb_groesse integer,
    h_intb_bran integer default 25,
    c_intb_bran character varying(8),
    intb_vonbetrieb date,
    intb_bisbetrieb date,
    zeitraum_bisheute boolean default false not null,
    zeitraum_bisjahr boolean default false not null,
    zeitraum_vonjahr boolean default false not null,
    relevant boolean default false,
    intb_schiessanlage_schusszahl integer,
    intb_schiessanlage_scheibenzahl integer,
    intb_schiessanlage_hat_kugelfang boolean,
    h_intb_schiessanlage_typ integer default 11410,
    c_intb_schiessanlage_typ text,
    h_intb_infg_vonbetrieb integer default 90,
    c_intb_infg_vonbetrieb character varying(8),
    h_intb_infg_bisbetrieb integer default 90,
    c_intb_infg_bisbetrieb character varying(8),
    intb_mobile_stoffe boolean,
    h_intb_res_abwbewe integer default 103,
    c_intb_res_abwbewe character varying(8),
    zentroid public.geometry(POINT, 2056),
    intb_eva character varying(100),
    h_intb_unterstand integer default 10023,
    c_intb_unterstand character varying(20),
    h_gem_id integer,
    h_intb_bran_noga integer default 25001,
    c_intb_bran_noga character varying(8),
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint pk_intb_intb_id primary key (intb_id),
    constraint fk_vflz_intb_vflz_id foreign key (vflz_id) references alma.vflz(vflz_id) on update cascade on delete cascade
);

comment on table alma.intb is 'Standorttyp-spezifische Daten zu Betrieben. Mehrere Datensaetze in intb zu einem Standort beschreiben verschiedene Betriebe.';

comment on column alma.intb.intb_id is 'primary key';
comment on column alma.intb.vflz_id is 'foreign key; alma.vflz';
comment on column alma.intb.intb_typ is 'Typ Betrieb (subset von vflz.c_vflz_vftyp): 02-Betrieb, 04-Schiessanlage';
comment on column alma.intb.intb_firma_name is 'Name der Firma';
comment on column alma.intb.intb_firma_strasse is 'Strasse der Firma';
comment on column alma.intb.intb_firma_plz is 'PLZ der Firma';
comment on column alma.intb.intb_firma_ort is 'Ort der Firma';
comment on column alma.intb.intb_groesse is 'Anzahl Mitarbeiter';
comment on column alma.intb.h_intb_bran is 'Codeliste Branche nach ASW';
comment on column alma.intb.c_intb_bran is 'Code Branche nach ASW';
comment on column alma.intb.intb_vonbetrieb is 'Betriebsbeginn';
comment on column alma.intb.intb_bisbetrieb is 'Betriebsende, NULL wird als Betrieb noch andauend interpretiert';
comment on column alma.intb.zeitraum_bisheute is 'Betrieb aktiv';
comment on column alma.intb.zeitraum_bisjahr is 'Jahr des Betriebsbeginn';
comment on column alma.intb.zeitraum_vonjahr is 'Jahr des Betriebsende';
comment on column alma.intb.relevant is 'Katasterrelevanz';
comment on column alma.intb.intb_schiessanlage_schusszahl is 'Schusszahl Schiessanlagen Typ';
comment on column alma.intb.intb_schiessanlage_scheibenzahl is 'Scheibenzahl Schiessanlagen Typ';
comment on column alma.intb.intb_schiessanlage_hat_kugelfang is 'Kugelfang Schiessanlagen Typ';
comment on column alma.intb.h_intb_schiessanlage_typ is 'Codelist Schiessanlagen Typ';
comment on column alma.intb.c_intb_schiessanlage_typ is 'Code Schiessanlagen Typ';
comment on column alma.intb.h_intb_infg_vonbetrieb is 'Codeliste Genauigkeit Betriebsbeginn';
comment on column alma.intb.c_intb_infg_vonbetrieb is 'Code Genauigkeit Betriebsbeginn';
comment on column alma.intb.h_intb_infg_bisbetrieb is 'Codeliste Genauigkeit Betriebsende';
comment on column alma.intb.c_intb_infg_bisbetrieb is 'Code Genauigkeit Betriebsende';
comment on column alma.intb.intb_mobile_stoffe is 'mobile Stoffe vorhanden';
comment on column alma.intb.h_intb_res_abwbewe is 'Codeliste Beurteilung des Betriebs';
comment on column alma.intb.c_intb_res_abwbewe is 'Code Beurteilung des Betriebs';
comment on column alma.intb.zentroid is 'Zentroid zur Lokalisierung des Betriebs';
comment on column alma.intb.intb_eva is 'Nummer des Betriebs nach EVA';
comment on column alma.intb.h_intb_unterstand is 'Codeliste Untersuchungsstand des Betriebs';
comment on column alma.intb.c_intb_unterstand is 'Code Untersuchungsstand des Betriebs';
comment on column alma.intb.h_gem_id is 'Gemeinde ID des Betriebs';
comment on column alma.intb.h_intb_bran_noga is 'Codeliste Branche nach NOGA';
comment on column alma.intb.c_intb_bran_noga is 'Code Branche nach NOGA';
comment on column alma.intb.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.intb.erfasser is 'Erfasser';
comment on column alma.intb.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.intb.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.intb.is_current is 'Aktuelle oder historisierte Version';

create index ix_fk_vflz_intb_vflz_id on alma.intb using btree (vflz_id);



create table alma.intu (
    intu_id integer not null generated by default as identity,
    vflz_id integer not null,
    intu_name character varying,
    intu_unfallvon date,
    zeitraum_jahr boolean default false not null,
    h_intu_infg_unfallvon integer default 90,
    c_intu_infg_unfallvon character varying(8),
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint pk_intu_intu_id primary key (intu_id),
    constraint fk_vflz_intu_vflz_id foreign key (vflz_id) references alma.vflz(vflz_id) on update cascade on delete cascade
);

comment on table alma.intu is 'Standorttyp-spezifische Daten zu Unfaellen. Mehrere Eintraege stehen fuer mehrere Unfaelle am Standort';

comment on column alma.intu.intu_id is 'primary key';
comment on column alma.intu.vflz_id is 'foreign key; alma.vflz';
comment on column alma.intu.intu_name is 'Name des Verursachers';
comment on column alma.intu.intu_unfallvon is 'Datum des Unfalls, Beginn';
comment on column alma.intu.zeitraum_jahr is 'Jahr des Unfalls, Beginn';
comment on column alma.intu.h_intu_infg_unfallvon is 'Codeliste Genauigkeit Unfallzeitpunkt';
comment on column alma.intu.c_intu_infg_unfallvon is 'Code Genauigkeit Unfallzeitpunkt';
comment on column alma.intu.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.intu.erfasser is 'Erfasser';
comment on column alma.intu.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.intu.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.intu.is_current is 'Aktuelle oder historisierte Version';

create index ix_fk_vflz_intu_vflz_id on alma.intu using btree (vflz_id);



create table alma.inum (
    inum_id integer not null generated by default as identity,
    intu_id integer not null,
    inum_stoffmng double precision,
    inum_ausgelaufen double precision,
    inum_zurueckgewonnen double precision,
    h_inum_stoffe integer default 117,
    c_inum_stoffe character varying(8),
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint pk_inum_inum_id primary key (inum_id),
    constraint fk_intu_inum_intu_id foreign key (intu_id) references alma.intu(intu_id) match full on update cascade on delete cascade
);

comment on table alma.inum is 'Standorttyp-spezifische Daten zu Unfaellen: Bei einem Unfall freigesetzte Stoffe';

comment on column alma.inum.inum_id is 'primary key';
comment on column alma.inum.intu_id is 'foreign key; alma.intu';
comment on column alma.inum.inum_stoffmng is 'Restmenge [l]; In der Umwelt verbliebene Stoffmenge';
comment on column alma.inum.inum_ausgelaufen is 'ausgelaufen [l]; Freigesetzte Stoffmenge';
comment on column alma.inum.inum_zurueckgewonnen is 'zurückgewonnen [l]; Zurueckgewonnene Stoffmenge';
comment on column alma.inum.h_inum_stoffe is 'Codeliste Stoffe und Stoffgemische';
comment on column alma.inum.c_inum_stoffe is 'Code Stoffe und Stoffgemische';
comment on column alma.inum.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.inum.erfasser is 'Erfasser';
comment on column alma.inum.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.inum.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.inum.is_current is 'Aktuelle oder historisierte Version';

create index ix_fk_intu_inum_intu_id on alma.inum using btree (intu_id);
