insert into alma.bemgrp (
    bemgrp_id,
    bemgrp,
    title,
    description,
    sort,
    public,
    key_column,
    rel_name,
    multiple,
    erfassungs_datum,
    erfasser,
    mutations_datum,
    mutierer
)
values
    (1, 'standort', 'Standort Bemerkungen', 'Bemerkungen zum gesamten Standort', 2, true, 'vflz_id', 'vflz', false, null, null, null, null),
    (2, 'betrieb', 'Betrieb Bemerkungen', 'Bemerkungen zum Betrieb', 99, true, 'intb_id', 'intb', false, null, null, null, null),
    (3, 'ablagerung', 'Ablagerung Bemerkungen', 'Bemerkungen zum Kompartiment', 99, true, 'inta_id', 'inta', false, null, null, null, null),
    (4, 'unfall', 'Unfall Bemerkungen', 'Bemerkungen zum Unfall', 99, true, 'intu_id', 'intu', false, null, null, null, null),
    (5, 'umwelt', 'Umwelt  Bemerkungen', 'Bemerkungen im Bereich Gefährung / Umwelt / Nutzung', 6, true, 'vflz_id', 'vflz', false, null, null, null, null),
    (6, 'subjekt', 'Subjekt Bemerkungen', 'Bemerkungen zum Subjekt', 99, true, 'subj_id', 'subj', false, null, null, null, null),
    (8, 'intern', 'Interne Anmerkungen', 'Interne Anmerkungen - nicht zur Veröffentlichung bestimmt', 1, false, 'vflz_id', 'vflz', true, null, null, null, null),
    (9, 'bere_begr_abwbewe', 'Begründung Bewertung', 'Begründung der manuellen Bewertung eines Standorts', 3, true, 'vflz_id', 'vflz', false, null, null, null, null),
    (10, 'bere_begr_prio_untersuch', 'Begründung Priorisierung Untersuchungsbedarf', 'Begründung zur Priorisierung des Untersuchungsbedarfs', 4, true, 'vflz_id', 'vflz', false, null, null, null, null),
    (11, 'bere_begr_prio_sanier', 'Begründung Prio. Überwachungsbe. / Sanierungsbe.', 'Begründung zur Priorisierung des Sanierungsbedarfs', 5, true, 'vflz_id', 'vflz', false, null, null, null, null),
    (12, 'pm_cache', 'Bemerkungen zu Aufgaben', 'Bemerkungen zu Aufgaben, nur intern', null, false, 'pm_cache_id', 'pm_cache', true, null, null, null, null),
    (13, 'mass.mass_id', 'Bemerkung Massnahme', 'Bemerkungen zur Umweltschutzmassnahme', 99, false, 'mass_id', 'mass', false, null, null, null, null),
    (14, 'sani.sani_id', 'Bemerkung Sanierung', 'Bemerkungen zur Sanierungsmassnahme', 99, false, 'sani_id', 'sani', false, null, null, null, null),
    (15, 'vfus.vfus_id', 'Bemerkung Umweltschaden', 'Bemerkungen zum Umweltschaden', 99, false, 'vfus_id', 'vfus', false, null, null, null, null),
    (16, 'veen.veen_id', 'Bemerkung Einzelereignis', 'Bemerkungen zum Ereignis / Vorkommnis', 99, false, 'veen_id', 'veen', false, null, null, null, null),
    (17, 'intb_begr_abwbewe', 'Begründung Bewertung Betrieb', 'Interne Begründung der Bewertung eines Betriebes', 99, false, 'intb_id', 'intb', false, null, null, null, null),
    (18, 'intk.intk_id', 'Bemerkung Kinderspielplatz/Grünfläche', 'Bemerkungen zu Kinderspielplätzen und Grünflächen', 99, false, 'intk_id', 'intk', false, null, null, null, null),
    (19, 'intk_begr_abwbewe', 'Begründung Bewertung Kinderspielplatz/Grünfläche', 'Interne Begründung der Bewertung eines Kinderspielplatzes / einer Grünfläche', 99, false, 'intk_id', 'intk', false, null, null, null, null),
    (20, 'intp.pfas_id', 'Bemerkung PFAS', 'Bemerkungen zu PFAS', 99, false, 'intp_id', 'intp', false, null, null, null, null),
    (21, 'intp_begr_abwbewe', 'Begründung Bewertung PFAS', 'Interne Begründung der Bewertung von PFAS', 99, false, 'intp_id', 'intp', false, null, null, null, null),
    (22, 'inta_datenimport', 'Bemerkung Datenimport Ablagerung', 'Bemerkungen zum Datenimport der Ablagerung', 99, false, 'inta_id', 'inta', false, null, null, null, null),
    (23, 'intb_datenimport', 'Bemerkung Datenimport Betrieb', 'Bemerkungen zum Datenimport des Betriebes', 99, false, 'intb_id', 'intb', false, null, null, null, null),
    (24, 'intu_datenimport', 'Bemerkung Datenimport Unfall', 'Bemerkungen zum Datenimport des Unfalls', 99, false, 'intu_id', 'intu', false, null, null, null, null),
    (25, 'ints_datenimport', 'Bemerkung Datenimport Schiessanlage', 'Bemerkungen zum Datenimport der Schiessanlage', 99, false, 'intb_id', 'intb', false, null, null, null, null),
    (26, 'intk_datenimport', 'Bemerkung Datenimport Kinderspielplatz/Grünfläche', 'Bemerkungen zum Datenimport von Kinderspielplätzen und Grünflächen', 99, false, 'intk_id', 'intk', false, null, null, null, null),
    (27, 'intp_datenimport', 'Bemerkung Datenimport PFAS', 'Bemerkungen zum Datenimport von PFAS', 99, false, 'intp_id', 'intp', false, null, null, null, null),
    (28, 'vflz_datenimport', 'Bemerkung Datenimport Standort', 'Bemerkungen zum Datenimport des Standorts', 99, false, 'vflz_id', 'vflz', false, null, null, null, null)
on conflict do nothing
;
