-- New combined Grundwasser table replacing gwnu + gwvk
create table alma.gwas (
    gwas_id integer not null generated by default as identity,
    vflz_id integer not null,
    h_gwas_relzugw integer default 71,
    c_gwas_relzugw character varying(8),
    gwas_flurabstand double precision,
    h_gwas_nutzung integer default 88,
    c_gwas_nutzung character varying(8),
    gwas_distanz integer,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint chk_gwas_h_gwas_relzugw check ((h_gwas_relzugw = 71)),
    constraint chk_gwas_h_gwas_nutzung check ((h_gwas_nutzung = 88)),
    constraint pk_gwas_gwas_id primary key (gwas_id),
    constraint fk_vflz_gwas_vflz_id foreign key (vflz_id) references alma.vflz(vflz_id) on update cascade on delete cascade
);

comment on table alma.gwas is 'Angaben zu Grundwasser (kombiniert aus gwvk und gwnu)';

comment on column alma.gwas.gwas_id is 'primary key';
comment on column alma.gwas.vflz_id is 'foreign key; alma.vflz';
comment on column alma.gwas.h_gwas_relzugw is 'Codeliste Relative Lage zum Grundwasser';
comment on column alma.gwas.c_gwas_relzugw is 'Code Relative Lage zum Grundwasser';
comment on column alma.gwas.gwas_flurabstand is 'Flurabstand [m]';
comment on column alma.gwas.h_gwas_nutzung is 'Codeliste Nutzung Grundwasser im Abstrombereich';
comment on column alma.gwas.c_gwas_nutzung is 'Code Nutzung Grundwasser im Abstrombereich';
comment on column alma.gwas.gwas_distanz is 'Distanz zur GW-Nutzung im Abstrombereich [m]';
comment on column alma.gwas.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.gwas.erfasser is 'Erfasser';
comment on column alma.gwas.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.gwas.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.gwas.is_current is 'Aktuelle oder historisierte Version';

create index idx_gwas_vflz_id on alma.gwas using btree (vflz_id);
