create table alma.vflgeo (
    vflgeo_id integer not null generated by default as identity,
    vflz_id integer not null,
    wkb_geometry public.geometry not null,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone default now(),
    mutierer text,
    is_current boolean not null default true,
    constraint enforce_dims_wkb_geometry check ((public.st_ndims(wkb_geometry) = 2)),
    constraint enforce_srid_wkb_geometry check ((public.st_srid(wkb_geometry) = 2056)),
    constraint pk_vflgeo_vflgeo_id primary key (vflgeo_id),
    constraint uq_vflgeo_vflz_id unique (vflz_id),
    constraint enforce_geometry_type_wkb_geometry check ((public.st_geometrytype(wkb_geometry) = any (array['ST_MultiPolygon'::text, 'ST_Point'::text]))),
    constraint fk_vflz_vflgeo_vflz_id foreign key (vflz_id) references alma.vflz(vflz_id) on update cascade on delete cascade
);

comment on table alma.vflgeo is 'Speichert die Standort-Geometrie bevorzugt als Polygon oder alternativ als Punkt';

comment on column alma.vflgeo.vflgeo_id IS 'primary key';
comment on column alma.vflgeo.vflz_id IS 'foreign key; alma.vflz';
comment on column alma.vflgeo.wkb_geometry IS 'Perimeter der Standortversion';
comment on column alma.vflgeo.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.vflgeo.erfasser is 'Erfasser';
comment on column alma.vflgeo.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.vflgeo.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.vflgeo.is_current is 'Aktuelle oder historisierte Version';

create index ix_fk_vflz_vflgeo_vflz_id on alma.vflgeo using btree (vflz_id);
create index ix_vflgeo_wkb_geometry on alma.vflgeo using gist (wkb_geometry);
