create table alma.bemgrp (
    bemgrp_id integer not null generated by default as identity,
    bemgrp character varying(50),
    title character varying(50),
    description character varying,
    sort integer,
    public boolean default false not null,
    key_column character varying(50) not null,
    rel_name character varying(50) not null,
    multiple boolean default false not null,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    constraint pk_bemgrp_bemgrp_id primary key (bemgrp_id),
    constraint uq_bemgrp_bemgrp unique (bemgrp)
);

comment on table alma.bemgrp is 'Kategorien der Bemerkungen';

comment on column alma.bemgrp.bemgrp_id is 'primary key';
comment on column alma.bemgrp.bemgrp is 'Bezeichnung der Bemerkungs-Kategorie. Tabelle alma.bem enthält alle Bemerkungen von unterschiedlichen Daten eines Standorts';
comment on column alma.bemgrp.title is 'Feldbezeichnung in der Anwendung';
comment on column alma.bemgrp.description is 'Beschreibung der Kategorie. Anzeige als Infotext in der Anwendung';
comment on column alma.bemgrp.sort is 'Sortierreihenfolge, wenn mehrere Bemerkungen aufgelistet sind';
comment on column alma.bemgrp.public is 'Filterkriterium zur Anzeige in öffentlichen Daten. Kommentare die public=true haben werden in den öffentlichen Reporten angezeigt';
comment on column alma.bemgrp.key_column is 'Foreign key: Spalte zur referenz Tabelle';
comment on column alma.bemgrp.rel_name is 'Foreign key: referenz Tabelle';
comment on column alma.bemgrp.multiple is 'Kennzeichen, um festzustellen, ob mehrere Anmerkungen pro Entität unterstützt werden';
comment on column alma.bemgrp.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.bemgrp.erfasser is 'Erfasser';
comment on column alma.bemgrp.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.bemgrp.mutierer is 'Bearbeiter der letzten Aenderung';

create index idx_bemgrp_bemgrp on alma.bemgrp using btree (bemgrp);



create table alma.bem (
    bem_id integer not null generated by default as identity,
    bemgrp_id integer not null,
    public boolean default false not null,
    sort integer,
    bem character varying not null,
    key_value integer,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint pk_bem_bem_id primary key (bem_id)
);

comment on table alma.bem is 'Alle Bemerkungen von unterschiedlichen Daten eines Standorts';

comment on column alma.bem.bem_id is 'primary key';
comment on column alma.bem.bemgrp_id is 'foreign key; alma.bemgrp';
comment on column alma.bem.public is 'Filterkriterium zur Anzeige in öffentlichen Daten. Kommentare die public=true haben werden in den öffentlichen Reporten angezeigt';
comment on column alma.bem.sort is 'Sortierreihenfolge, wenn mehrere Bemerkungen aufgelistet sind';
comment on column alma.bem.bem is 'Bemerkungs-Text.';
comment on column alma.bem.key_value is 'Schhlüsselwert für die Zuordnung der referenzierten Tabelle in bemgrp.key_column und bemgrp.rel_name';
comment on column alma.bem.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.bem.erfasser is 'Erfasser';
comment on column alma.bem.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.bem.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.bem.is_current is 'Aktuelle oder historisierte Version';

create index idx_bem_bem_id on alma.bem using btree (bem_id);
create index idx_bem_key_value_bemgrp_id on alma.bem using btree (key_value, bemgrp_id);
