create table alma.gwnu (
    gwnu_id integer not null generated by default as identity,
    vflz_id integer not null,
    h_gwnu_nutzung integer default 88,
    c_gwnu_nutzung character varying(8),
    gwnu_distanz integer,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint chk_gwnu_h_gwnu_nutzung check ((h_gwnu_nutzung = 88)),
    constraint pk_gwnu_gwnu_id primary key (gwnu_id),
    constraint fk_vflz_gwnu_vflz_id foreign key (vflz_id) references alma.vflz(vflz_id) on update cascade on delete cascade,
    constraint uq_gwnu_vflz_id unique (vflz_id)
);

comment on table alma.gwnu is 'Angaben Grundwasser im Abstrombereich';

comment on column alma.gwnu.gwnu_id is 'primary key';
comment on column alma.gwnu.vflz_id is 'foreign key; alma.vflz';
comment on column alma.gwnu.h_gwnu_nutzung is 'Codeliste Nutzung Grundwasser im Abstrombereich';
comment on column alma.gwnu.c_gwnu_nutzung is 'Code Nutzung Grundwasser im Abstrombereich';
comment on column alma.gwnu.gwnu_distanz is 'Distanz zur GW-Nutzung im Abstrombereich [m]';
comment on column alma.gwnu.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.gwnu.erfasser is 'Erfasser';
comment on column alma.gwnu.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.gwnu.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.gwnu.is_current is 'Aktuelle oder historisierte Version';

create index idx_gwnu_vflz_id on alma.gwnu using btree (vflz_id);
create index ix_fk_vflz_gwnu_vflz_id on alma.gwnu using btree (vflz_id);



create table alma.gwvk (
    gwvk_id integer not null generated by default as identity,
    vflz_id integer not null,
    h_gwvk_relzugw integer default 71,
    c_gwvk_relzugw character varying(8),
    gwvk_flurabstand double precision,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint chk_gwvk_h_gwvk_relzugw check ((h_gwvk_relzugw = 71)),
    constraint pk_gwvk_gwvk_id primary key (gwvk_id),
    constraint fk_vflz_gwvk_vflz_id foreign key (vflz_id) references alma.vflz(vflz_id) on update cascade on delete cascade,
    constraint uq_gwvk_vflz_id unique (vflz_id)
);

comment on table alma.gwvk is 'Angaben zu Grundwasservorkommen';

comment on column alma.gwvk.gwvk_id is 'primary key';
comment on column alma.gwvk.vflz_id is 'foreign key; alma.vflz';
comment on column alma.gwvk.c_gwvk_relzugw is 'Codeliste Relative Lage zum Grundwasser';
comment on column alma.gwvk.c_gwvk_relzugw is 'Code Relative Lage zum Grundwasser';
comment on column alma.gwvk.gwvk_flurabstand is 'Flurabstand [m]';
comment on column alma.gwnu.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.gwnu.erfasser is 'Erfasser';
comment on column alma.gwnu.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.gwnu.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.gwnu.is_current is 'Aktuelle oder historisierte Version';

create index ix_fk_vflz_gwvk_vflz_id on alma.gwvk using btree (vflz_id);



create table alma.nubo (
    nubo_id integer not null generated by default as identity,
    vflz_id integer not null,
    h_nubo_nutzungsart integer default 87,
    c_nubo_nutzungsart character varying(8) default '06'::character varying,
    h_nubo_akt_nutzung integer,
    c_nubo_akt_nutzung character varying(8),
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint pk_nubo_nubo_id primary key (nubo_id),
    constraint fk_vflz_nubo_vflz_id foreign key (vflz_id) references alma.vflz(vflz_id) on update cascade on delete cascade
);

comment on table alma.nubo is 'Aktuelle Nutzung des Gelaendes';

comment on column alma.nubo.nubo_id is 'primary key';
comment on column alma.nubo.vflz_id is 'foreign key; alma.vflz';
comment on column alma.nubo.h_nubo_nutzungsart is 'Codeliste Nutzungsart';
comment on column alma.nubo.c_nubo_nutzungsart is 'Code Nutzungsart';
comment on column alma.nubo.h_nubo_akt_nutzung is 'Codeliste Aktuelle Nutzung - Codeliste in Abhaengigkeit der Nutzungsart.';
comment on column alma.nubo.c_nubo_akt_nutzung is 'Code Aktuelle Nutzung - Codeliste in Abhaengigkeit der Nutzungsart.';
comment on column alma.nubo.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.nubo.erfasser is 'Erfasser';
comment on column alma.nubo.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.nubo.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.nubo.is_current is 'Aktuelle oder historisierte Version';

create index ix_fk_vflz_nubo_vflz_id on alma.nubo using btree (vflz_id);



create table alma.ogw (
    ogw_id integer not null generated by default as identity,
    vflz_id integer not null,
    ogw_name character varying(100),
    ogw_distanz integer,
    h_ogw_art_gewaesser integer default 66,
    c_ogw_art_gewaesser character varying(8) default '05'::character varying,
    h_ogw_bau_gewaesser integer default 67,
    c_ogw_bau_gewaesser character varying(8) default '04'::character varying,
    h_ogw_rellage integer default 70,
    c_ogw_rellage character varying(8) default '04'::character varying,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint chk_ogw_h_ogw_art_gewaesser check ((h_ogw_art_gewaesser = 66)),
    constraint chk_ogw_h_ogw_bau_gewaesser check ((h_ogw_bau_gewaesser = 67)),
    constraint chk_ogw_h_ogw_rellage check ((h_ogw_rellage = 70)),
    constraint pk_ogw_ogw_id primary key (ogw_id),
    constraint fk_vflz_ogw_vflz_id foreign key (vflz_id) references alma.vflz(vflz_id) on update cascade on delete cascade,
    constraint uq_ogw_vflz_id unique (vflz_id)
);

comment on table alma.ogw is 'Angaben zu Oberflaechengewaessern';

comment on column alma.ogw.ogw_id is 'primary key';
comment on column alma.ogw.vflz_id is 'foreign key; alma.vflz';
comment on column alma.ogw.ogw_name is 'Name des Oberflaechengewaessers';
comment on column alma.ogw.ogw_distanz is 'Distanz zum Oberflaechengewaesser [m]';
comment on column alma.ogw.h_ogw_art_gewaesser is 'Codeliste Gewaesserart';
comment on column alma.ogw.c_ogw_art_gewaesser is 'Code Gewaesserart';
comment on column alma.ogw.h_ogw_bau_gewaesser is 'Codeliste Gewaesserbau';
comment on column alma.ogw.c_ogw_bau_gewaesser is 'Code Gewaesserbau';
comment on column alma.ogw.h_ogw_rellage is 'Codeeliste Relative Lage zum Oberflaechengewaesser';
comment on column alma.ogw.c_ogw_rellage is 'Code Relative Lage zum Oberflaechengewaesser';
comment on column alma.ogw.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.ogw.erfasser is 'Erfasser';
comment on column alma.ogw.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.ogw.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.ogw.is_current is 'Aktuelle oder historisierte Version';

create index ix_fk_vflz_ogw_vflz_id on alma.ogw using btree (vflz_id);



create table alma.stoffe (
    stoffe_id integer not null generated by default as identity,
    vflz_id integer not null,
    h_stoffe_umweltbereich integer default 299,
    c_stoffe_umweltbereich character varying(8),
    h_stoffe_gruppe integer default 300,
    c_stoffe_gruppe character varying(8),
    h_stoffe_stoff integer,
    c_stoffe_stoff character varying(8),
    h_stoffe_beurteilung integer default 330,
    c_stoffe_beurteilung character varying(8),
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint chk_stoffe_h_stoffe_umweltbereich check ((h_stoffe_umweltbereich = 299)),
    constraint chk_stoffe_h_stoffe_gruppe check ((h_stoffe_gruppe = 300)),
    constraint chk_stoffe_h_stoffe_beurteilung check ((h_stoffe_beurteilung = 330)),
    constraint pk_stoffe_stoffe_id primary key (stoffe_id),
    constraint fk_vflz_stoffe_vflz_id foreign key (vflz_id) references alma.vflz(vflz_id) on update cascade on delete cascade
);

comment on table alma.stoffe is 'Umweltrelevante Stoffe';

comment on column alma.stoffe.stoffe_id is 'primary key';
comment on column alma.stoffe.vflz_id is 'foreign key; alma.vflz';
comment on column alma.stoffe.h_stoffe_umweltbereich is 'Codeliste Beeintraechtigung Umweltbereiche';
comment on column alma.stoffe.c_stoffe_umweltbereich is 'Code Beeintraechtigung Umweltbereiche';
comment on column alma.stoffe.h_stoffe_gruppe is 'Codeliste Stoffgruppe';
comment on column alma.stoffe.c_stoffe_gruppe is 'Code Stoffgruppe';
comment on column alma.stoffe.h_stoffe_stoff is 'Codeliste Stoffe';
comment on column alma.stoffe.c_stoffe_stoff is 'Code Stoffe';
comment on column alma.stoffe.h_stoffe_beurteilung is 'Codeliste Beurteilung zur Erfassung der Stoffe';
comment on column alma.stoffe.c_stoffe_beurteilung is 'Code Beurteilung zur Erfassung der Stoffe';
comment on column alma.stoffe.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.stoffe.erfasser is 'Erfasser';
comment on column alma.stoffe.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.stoffe.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.stoffe.is_current is 'Aktuelle oder historisierte Version';

create index ix_fk_vflz_stoffe_vflz_id on alma.stoffe using btree (vflz_id);



create table alma.veen (
    veen_id integer generated by default as identity,
    vflz_id integer not null,
    h_veen_natuerlich integer default 61,
    c_veen_natuerlich character varying(8),
    veen_datum date,
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer character varying,
    is_current boolean not null default true,
    constraint chk_veen_h_veen_natuerlich check ((h_veen_natuerlich = 61)),
    constraint pk_veen_veen_id primary key (veen_id),
    constraint fk_vflz_veen_vflz_id foreign key (vflz_id) references alma.vflz(vflz_id) on update cascade on delete cascade
);

comment on table alma.veen is 'Einzelereignisse natuerlich';

comment on column alma.veen.veen_id is 'primary key';
comment on column alma.veen.vflz_id is 'foreign key; alma.vflz';
comment on column alma.veen.h_veen_natuerlich is 'Codeliste Einzelereignisse';
comment on column alma.veen.c_veen_natuerlich is 'Code Einzelereignisse';
comment on column alma.veen.veen_datum is 'Datum des Einzelereignisses';
comment on column alma.veen.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.veen.erfasser is 'Erfasser';
comment on column alma.veen.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.veen.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.veen.is_current is 'Aktuelle oder historisierte Version';

create index ix_fk_vflz_veen_vflz_id on alma.veen using btree (vflz_id);



create table alma.vfus (
    vfus_id integer generated by default as identity,
    vflz_id integer not null,
    h_vfus_art_schaden integer default 101,
    c_vfus_art_schaden character varying(8) default '01'::character varying,
    h_vfus_schaeden integer,
    c_vfus_schaeden character varying(8),
    erfassungs_datum timestamp without time zone default now(),
    erfasser text,
    mutations_datum timestamp without time zone,
    mutierer text,
    is_current boolean not null default true,
    constraint chk_vfus_h_vfus_art_schaden check ((h_vfus_art_schaden = 101)),
    constraint chk_vfus_h_vfus_schaeden_filled check ((((h_vfus_schaeden is null) and (c_vfus_schaeden is null)) or (h_vfus_schaeden is not null))),
    constraint pk_vfus_vfus_id primary key (vfus_id),
    constraint fk_vflz_vfus_vflz_id foreign key (vflz_id) references alma.vflz(vflz_id) on update cascade on delete cascade
);

comment on table alma.vfus is 'Umweltschaeden';

comment on column alma.vfus.vfus_id is 'primary key';
comment on column alma.vfus.vflz_id is 'foreign key; alma.vflz';
comment on column alma.vfus.h_vfus_art_schaden is 'Codeliste Umweltbereiche';
comment on column alma.vfus.c_vfus_art_schaden is 'Code Umweltbereiche';
comment on column alma.vfus.h_vfus_schaeden is 'Codeliste Umweltschaeden';
comment on column alma.vfus.c_vfus_schaeden is 'Umweltschaeden. - Codeliste in Abhaengigkeit zum Umweltbereich.';
comment on column alma.vfus.erfassungs_datum is 'Datum der Erfassung';
comment on column alma.vfus.erfasser is 'Erfasser';
comment on column alma.vfus.mutations_datum is 'Datum der letzten Aenderung';
comment on column alma.vfus.mutierer is 'Bearbeiter der letzten Aenderung';
comment on column alma.vfus.is_current is 'Aktuelle oder historisierte Version';

create index ix_fk_vflz_vfus_vflz_id on alma.vfus using btree (vflz_id);
