CREATE TABLE alma_admin.auth_role (
    id BIGSERIAL NOT NULL,
    name VARCHAR NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_auth_role_id PRIMARY KEY (id),
    CONSTRAINT uq_auth_role_name UNIQUE ("name")
);

comment on table alma_admin.auth_role is 'Store role information';
comment on column alma_admin.auth_role.id is 'Primary key';
comment on column alma_admin.auth_role.name is 'Name of role (unique)';
comment on column alma_admin.auth_role.created_at is 'Creation timestamp';
comment on column alma_admin.auth_role.updated_at is 'Update timestamp';


INSERT INTO alma_admin.auth_role (name) VALUES
    ('LESEN_SACHDATEN'),
    ('LESEN_GESCHAEFTE'),
    ('BEARBEITEN_SACHDATEN'),
    ('BEARBEITEN_GESCHAEFTE'),
    ('ADMINISTRATION')
;


CREATE TABLE alma_admin.auth_user (
    id BIGSERIAL NOT NULL,
    sub VARCHAR NOT NULL,
    username VARCHAR NOT NULL,
    role_id BIGINT,
    email VARCHAR NOT NULL,
    first_name VARCHAR DEFAULT '' NOT NULL,
    last_name VARCHAR DEFAULT '' NOT NULL,
    is_sachbearbeitung BOOLEAN DEFAULT false NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_auth_user_id PRIMARY KEY (id),
    CONSTRAINT uq_auth_user_email UNIQUE (email),
    CONSTRAINT uq_auth_user_username UNIQUE (username),
    CONSTRAINT uq_auth_user_sub UNIQUE (sub),
    CONSTRAINT fk_auth_role_auth_user_role_id FOREIGN KEY(role_id) REFERENCES alma_admin.auth_role (id) ON DELETE SET NULL
);

comment on table alma_admin.auth_user is 'Store user information';
comment on column alma_admin.auth_user.id is 'Primary key';
comment on column alma_admin.auth_user.sub is 'Unique identifier provided by SSO.';
comment on column alma_admin.auth_user.username is 'Username';
comment on column alma_admin.auth_user.role_id is 'Foreign key to role';
comment on column alma_admin.auth_user.email is 'Unique E-Mail-Adress';
comment on column alma_admin.auth_user.first_name is 'First name';
comment on column alma_admin.auth_user.last_name is 'Last name';
comment on column alma_admin.auth_user.is_sachbearbeitung is 'Kann Sachbearbeiter sein';
comment on column alma_admin.auth_user.created_at is 'Creation timestamp';
comment on column alma_admin.auth_user.updated_at is 'Update timestamp';

create table alma_admin.oidc_session (
    id integer not null generated by default as identity,
    session_key varchar not null,
    expires_at timestamp with time zone not null,
    token varchar not null,
    user_id bigint not null,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    constraint pk_oidc_session_id primary key (id),
    constraint uq_oidc_session_session_key unique (session_key),
    constraint fk_oidc_session_auth_user_user_id foreign key (user_id) references alma_admin.auth_user (id) on delete cascade,
    constraint ck_oidc_session_session_key_length check (length(session_key) >= 32)
);

comment on table alma_admin.oidc_session is 'Stores OIDC session information.';
comment on column alma_admin.oidc_session.id is 'Primary key';
comment on column alma_admin.oidc_session.session_key is 'Unique session key as identifier';
comment on column alma_admin.oidc_session.expires_at is 'Expiry timestamp of session';
comment on column alma_admin.oidc_session.token is 'Authentication token';
comment on column alma_admin.oidc_session.user_id is 'Foreign key to associated user';
comment on column alma_admin.oidc_session.created_at is 'Creation timestamp';
comment on column alma_admin.oidc_session.updated_at is 'Update timestamp';


create table alma_admin.settings (
    id integer not null generated by default as identity,
    key varchar not null,
    value jsonb not null,
    value_schema jsonb not null,
    category varchar not null,
    constraint uq_settings_key_category unique (key, category),
    constraint ck_settings_category check (category = 'ADMIN' or category = 'GENERAL'),
    constraint pk_settings_id primary key (id)
);

comment on table alma_admin.settings is 'Stores configurable settings (key, value store).';
comment on column alma_admin.settings.id is 'Primary key';
comment on column alma_admin.settings.key is 'Identifier of setting';
comment on column alma_admin.settings.value is 'Actual value of setting';
comment on column alma_admin.settings.value_schema is 'JSON schema of setting value';
comment on column alma_admin.settings.category is 'Specifies if modifiable by admin or all user roles';



create table alma_admin.user_settings (
    id integer not null generated by default as identity,
    key varchar not null,
    value jsonb not null,
    user_id bigint not null,
    constraint uq_user_settings_user_id_key unique (user_id, key),
    constraint pk_user_settings_id primary key (id),
    constraint fk_auth_user_user_settings_user_id foreign key(user_id) references alma_admin.auth_user (id) on delete cascade
);

comment on table alma_admin.user_settings is 'Stores user-specific settings.';
comment on column alma_admin.user_settings.id is 'Primary key';
comment on column alma_admin.user_settings.key is 'Identifier of setting';
comment on column alma_admin.user_settings.value is 'Actual value of setting';
comment on column alma_admin.user_settings.user_id is 'Foreign key to user';
