# Supervisor config to manage a group of procrastinate worker processes.
# This is used in the "scheduler" container.
#
# See https://docs.docker.com/engine/containers/multi-service_container/

[supervisord]
nodaemon = true
user = app
logfile = /dev/null
logfile_maxbytes = 0

[unix_http_server]
file = /tmp/supervisor.sock

[program:worker]
command = /app/venv/bin/procrastinate --app=alma.task_queue.app worker
environment = PYTHONDONTWRITEBYTECODE="1",PYTHONUNBUFFERED="1",PROCRASTINATE_WORKER_NAME="worker-%(process_num)s"
stdout_logfile = /dev/fd/1
stdout_logfile_maxbytes = 0
redirect_stderr = true
autostart = true
autorestart = true
numprocs = 2
process_name = worker-%(process_num)s
