server {
    listen 80;
    listen [::]:80;
    server_name localhost;

    root /var/www/alma-frontend/;
    proxy_read_timeout 120;
    client_max_body_size 40M;
    set_real_ip_from 10.1.0.1;
    set_real_ip_from 10.1.0.5;
    set_real_ip_from 10.1.0.7;
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;


    location ~ ^(/api/.*|/graphql|/openapi\.json)$ {
        proxy_pass http://backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $http_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_cache_bypass $http_upgrade;
    }

    location /mapserver {
        # proxy
        proxy_pass http://mapserver:8081/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $http_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_cache_bypass $http_upgrade;

        # Allow access from whitelisted IP *or* using HTTP auth;
        satisfy any;

        include /etc/nginx/allow_ips.conf;

        deny all;

        include /etc/nginx/kbs_mapserver.conf;
    }

    location /auth/ {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Forwarded-For $http_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        # TODO: enable this for internal IP addresses:
        # uncomment the following line if you want to use the keycloak admin UI:
        proxy_pass http://keycloak:8080/auth/;

        location /auth/realms/alma/ {
            proxy_pass http://keycloak:8080/auth/realms/alma/;
        }

        location /auth/resources/ {
            proxy_pass http://keycloak:8080/auth/resources/;
        }

        location /auth/js/ {
            proxy_pass http://keycloak:8080/auth/js/;
        }

        location /auth/robots.txt {
            proxy_pass http://keycloak:8080/auth/robots.txt;
        }
    }

    include /srv/alma/next-routes.conf;

    location / {
        try_files $uri $uri/ @rewrites;
    }

    # match for filename in capture group 1
    location ~ ^/interlis_exports/(?<target>[a-zA-Z0-9-_\.%\/]+)$ {
        root /var/www/interlis_exports;
        autoindex off;

        if ($request_uri ~ \.\.) {
            # prevent directory traversal
            return 403;
        }
        try_files /$target =404; # do send an actual 404 if not found

        include /etc/nginx/interlis_exports.conf;
    }

    # match for filename in capture group 1
    location ~ ^/kbs/(?<target>[a-zA-Z0-9-_\.%\/]+)$ {
        root /var/www/report_exports;
        autoindex off;

        if ($request_uri ~ \.\.) {
            # prevent directory traversal
            return 403;
        }
        try_files /$target =404; # do send an actual 404 if not found

        include /etc/nginx/report_exports.conf;
    }

    location @rewrites {
        rewrite ^(.+)$ /404.html last;
    }

}
