create temporary table flugplatz_import (
    h_flugplatz_id integer,
    bezeichnung text,
    art text,
    icao text,
    abk text,
    c_kt text,
    zusatz text,
    wkb_geometry text
);

\copy flugplatz_import from '/include/flugplaetze.csv' with delimiter ',' csv header;

delete from alma.flugplatz;

insert into alma.flugplatz (flugplatz_id, art, h_flugplatz_bezeichnung, c_flugplatz_bezeichnung, icao, abk, c_kt, zusatz, wkb_geometry)
select
    h_flugplatz_id
    , art
    , 600 as h_flugplatz_bezeichnung
    , icao as c_flugplatz_bezeichnung
    , icao
    , abk
    , c_kt
    , zusatz
    , ST_SetSRID(wkb_geometry, 2056)
from flugplatz_import;

insert into alma.c_cli (c_cli_id, bezeichnung, c_status)
values (600,'Flugplatz', true);

insert into alma.cod (c_cli_id, code, bemerkungen)
select
    600 as c_cli_id
    , icao as code
    , bezeichnung as bemerkungen
from flugplatz_import;

insert into alma.translations (msgid, msgstr, locale)
values
    -- German
    ('code:600:LSZH', 'Zürich', 'de'),
    ('code:600:NA2', 'Sembrancher', 'de'),
    ('code:600:LSGY', 'Yverdon', 'de'),
    ('code:600:LSTS', 'St.Stephan', 'de'),
    ('code:600:LSZJ', 'Courtelary', 'de'),
    ('code:600:LSTR', 'Montricher', 'de'),
    ('code:600:LSTO', 'Môtiers', 'de'),
    ('code:600:LSPU', 'Münster', 'de'),
    ('code:600:LSZA', 'Lugano-Agno', 'de'),
    ('code:600:LSZD', 'Ascona', 'de'),
    ('code:600:LSPM', 'Ambrì', 'de'),
    ('code:600:LSPA', 'Amlikon', 'de'),
    ('code:600:LSZE', 'Bad Ragaz', 'de'),
    ('code:600:LSTB', 'Bellechasse', 'de'),
    ('code:600:LSPL', 'Langenthal', 'de'),
    ('code:600:LSZT', 'Lommis', 'de'),
    ('code:600:LSZR', 'St.Gallen-Altenrhein', 'de'),
    ('code:600:LSWS', 'Schwarzsee', 'de'),
    ('code:600:LSZM', 'Mollis', 'de'),
    ('code:600:LSPK', 'Hasenstrick', 'de'),
    ('code:600:LSXB', 'Balzers', 'de'),
    ('code:600:LSGC', 'La Chaux-de-Fonds-Les Eplatures', 'de'),
    ('code:600:LSGP', 'La Côte', 'de'),
    ('code:600:LSGL', 'Lausanne-La Blécherette', 'de'),
    ('code:600:LSZB', 'Bern-Belp', 'de'),
    ('code:600:LSGB', 'Bex', 'de'),
    ('code:600:LSZO', 'Luzern-Beromünster', 'de'),
    ('code:600:LSZF', 'Birrfeld', 'de'),
    ('code:600:LSZQ', 'Bressaucourt', 'de'),
    ('code:600:LSZU', 'Buttwil', 'de'),
    ('code:600:NA1', 'Davos', 'de'),
    ('code:600:LSPD', 'Dittingen', 'de'),
    ('code:600:LSXU', 'Untervaz', 'de'),
    ('code:600:LSPV', 'Wangen-Lachen', 'de'),
    ('code:600:LSPH', 'Winterthur', 'de'),
    ('code:600:LSGE', 'Ecuvillens', 'de'),
    ('code:600:LSME', 'Emmen', 'de'),
    ('code:600:LSXE', 'Erstfeld', 'de'),
    ('code:600:LSZI', 'Fricktal-Schupfart', 'de'),
    ('code:600:LSGG', 'Genève', 'de'),
    ('code:600:LSGN', 'Neuchâtel', 'de'),
    ('code:600:LSEG', 'Gampel', 'de'),
    ('code:600:LSXO', 'Gossau', 'de'),
    ('code:600:LSZN', 'Hausen a.A.', 'de'),
    ('code:600:LSZG', 'Grenchen', 'de'),
    ('code:600:LSGT', 'Gruyères', 'de'),
    ('code:600:LSPO', 'Olten', 'de'),
    ('code:600:LSXG', 'Gsteigwiler', 'de'),
    ('code:600:LSXN', 'Haltikon', 'de'),
    ('code:600:LSXH', 'Holziken', 'de'),
    ('code:600:LSXI', 'Interlaken', 'de'),
    ('code:600:LSPG', 'Kägiswil', 'de'),
    ('code:600:LSZX', 'Schänis', 'de'),
    ('code:600:LSXL', 'Lauterbrunnen', 'de'),
    ('code:600:LSZP', 'Biel-Kappelen', 'de'),
    ('code:600:LSTA', 'Raron-Flugfeld', 'de'),
    ('code:600:LSER', 'Raron-Heliport', 'de'),
    ('code:600:LSZL', 'Locarno', 'de'),
    ('code:600:LSML', 'Lodrino-Flugfeld', 'de'),
    ('code:600:LSXP', 'Pfaffnau', 'de'),
    ('code:600:LSGR', 'Reichenbach', 'de'),
    ('code:600:LSGK', 'Saanen', 'de'),
    ('code:600:LSZS', 'Samedan', 'de'),
    ('code:600:LSXV', 'San Vittore', 'de'),
    ('code:600:LSPF', 'Schaffhausen', 'de'),
    ('code:600:LSWL', 'Lauberhorn', 'de'),
    ('code:600:LSXC', 'Schattenhalb', 'de'),
    ('code:600:LSXS', 'Schindellegi', 'de'),
    ('code:600:LSGS', 'Sion', 'de'),
    ('code:600:LSZV', 'Sitterdorf', 'de'),
    ('code:600:LSZK', 'Speck-Fehraltorf', 'de'),
    ('code:600:LSXM', 'St.Moritz', 'de'),
    ('code:600:LSXA', 'Tavanasa', 'de'),
    ('code:600:LSZW', 'Thun', 'de'),
    ('code:600:LSPN', 'Triengen', 'de'),
    ('code:600:LSZC', 'Buochs', 'de'),
    ('code:600:LSXT', 'Trogen', 'de'),
    ('code:600:LSXW', 'Würenlingen', 'de'),
    ('code:600:LSEZ', 'Zermatt', 'de'),
    ('code:600:LSMP', 'Payerne', 'de'),
    ('code:600:LSTZ', 'Zweisimmen', 'de'),
    ('code:600:LSEC', 'Collombey-Muraz', 'de'),
    ('code:600:LSWB', 'Blumenstein', 'de'),
    ('code:600:LSWM', 'Männlichen', 'de'),
    ('code:600:LSXD', 'Domat-Ems', 'de'),
    ('code:600:LSZY', 'Porrentruy', 'de'),
    ('code:600:LSXK', 'Benken', 'de'),
    ('code:600:LSXR', 'Lodrino-Heliport', 'de'),
    ('code:600:LSEA', 'Gstaad-Inn Grund', 'de'),
    ('code:600:LSEY', 'Leysin', 'de'),
    ('code:600:LSPW', 'Wangen', 'de'),

    -- French
    ('code:600:LSZH', 'Zurich', 'fr'),
    ('code:600:NA2', 'Sembrancher', 'fr'),
    ('code:600:LSGY', 'Yverdon', 'fr'),
    ('code:600:LSTS', 'Saint-Stephan', 'fr'),
    ('code:600:LSZJ', 'Courtelary', 'fr'),
    ('code:600:LSTR', 'Montricher', 'fr'),
    ('code:600:LSTO', 'Môtiers', 'fr'),
    ('code:600:LSPU', 'Münster', 'fr'),
    ('code:600:LSZA', 'Lugano-Agno', 'fr'),
    ('code:600:LSZD', 'Ascona', 'fr'),
    ('code:600:LSPM', 'Ambrì', 'fr'),
    ('code:600:LSPA', 'Amlikon', 'fr'),
    ('code:600:LSZE', 'Bad Ragaz', 'fr'),
    ('code:600:LSTB', 'Bellechasse', 'fr'),
    ('code:600:LSPL', 'Langenthal', 'fr'),
    ('code:600:LSZT', 'Lommis', 'fr'),
    ('code:600:LSZR', 'Saint-Gall-Altenrhein', 'fr'),
    ('code:600:LSWS', 'Schwarzsee', 'fr'),
    ('code:600:LSZM', 'Mollis', 'fr'),
    ('code:600:LSPK', 'Hasenstrick', 'fr'),
    ('code:600:LSXB', 'Balzers', 'fr'),
    ('code:600:LSGC', 'La Chaux-de-Fonds-Les Eplatures', 'fr'),
    ('code:600:LSGP', 'La Côte', 'fr'),
    ('code:600:LSGL', 'Lausanne-La Blécherette', 'fr'),
    ('code:600:LSZB', 'Berne-Belp', 'fr'),
    ('code:600:LSGB', 'Bex', 'fr'),
    ('code:600:LSZO', 'Lucerne-Beromünster', 'fr'),
    ('code:600:LSZF', 'Birrfeld', 'fr'),
    ('code:600:LSZQ', 'Bressaucourt', 'fr'),
    ('code:600:LSZU', 'Buttwil', 'fr'),
    ('code:600:NA1', 'Davos', 'fr'),
    ('code:600:LSPD', 'Dittingen', 'fr'),
    ('code:600:LSXU', 'Untervaz', 'fr'),
    ('code:600:LSPV', 'Wangen-Lachen', 'fr'),
    ('code:600:LSPH', 'Winterthour', 'fr'),
    ('code:600:LSGE', 'Ecuvillens', 'fr'),
    ('code:600:LSME', 'Emmen', 'fr'),
    ('code:600:LSXE', 'Erstfeld', 'fr'),
    ('code:600:LSZI', 'Fricktal-Schupfart', 'fr'),
    ('code:600:LSGG', 'Genève', 'fr'),
    ('code:600:LSGN', 'Neuchâtel', 'fr'),
    ('code:600:LSEG', 'Gampel', 'fr'),
    ('code:600:LSXO', 'Gossau', 'fr'),
    ('code:600:LSZN', 'Hausen a.A.', 'fr'),
    ('code:600:LSZG', 'Granges', 'fr'),
    ('code:600:LSGT', 'Gruyères', 'fr'),
    ('code:600:LSPO', 'Olten', 'fr'),
    ('code:600:LSXG', 'Gsteigwiler', 'fr'),
    ('code:600:LSXN', 'Haltikon', 'fr'),
    ('code:600:LSXH', 'Holziken', 'fr'),
    ('code:600:LSXI', 'Interlaken', 'fr'),
    ('code:600:LSPG', 'Kägiswil', 'fr'),
    ('code:600:LSZX', 'Schänis', 'fr'),
    ('code:600:LSXL', 'Lauterbrunnen', 'fr'),
    ('code:600:LSZP', 'Bienne-Kappelen', 'fr'),
    ('code:600:LSTA', 'Rarogne-Aérodrome', 'fr'),
    ('code:600:LSER', 'Rarogne-Héliport', 'fr'),
    ('code:600:LSZL', 'Locarno', 'fr'),
    ('code:600:LSML', 'Lodrino-Aérodrome', 'fr'),
    ('code:600:LSXP', 'Pfaffnau', 'fr'),
    ('code:600:LSGR', 'Reichenbach', 'fr'),
    ('code:600:LSGK', 'Saanen', 'fr'),
    ('code:600:LSZS', 'Samedan', 'fr'),
    ('code:600:LSXV', 'San Vittore', 'fr'),
    ('code:600:LSPF', 'Schaffhouse', 'fr'),
    ('code:600:LSWL', 'Lauberhorn', 'fr'),
    ('code:600:LSXC', 'Schattenhalb', 'fr'),
    ('code:600:LSXS', 'Schindellegi', 'fr'),
    ('code:600:LSGS', 'Sion', 'fr'),
    ('code:600:LSZV', 'Sitterdorf', 'fr'),
    ('code:600:LSZK', 'Speck-Fehraltorf', 'fr'),
    ('code:600:LSXM', 'Saint-Moritz', 'fr'),
    ('code:600:LSXA', 'Tavanasa', 'fr'),
    ('code:600:LSZW', 'Thoune', 'fr'),
    ('code:600:LSPN', 'Triengen', 'fr'),
    ('code:600:LSZC', 'Buochs', 'fr'),
    ('code:600:LSXT', 'Trogen', 'fr'),
    ('code:600:LSXW', 'Würenlingen', 'fr'),
    ('code:600:LSEZ', 'Zermatt', 'fr'),
    ('code:600:LSMP', 'Payerne', 'fr'),
    ('code:600:LSTZ', 'Zweisimmen', 'fr'),
    ('code:600:LSEC', 'Collombey-Muraz', 'fr'),
    ('code:600:LSWB', 'Blumenstein', 'fr'),
    ('code:600:LSWM', 'Männlichen', 'fr'),
    ('code:600:LSXD', 'Domat-Ems', 'fr'),
    ('code:600:LSZY', 'Porrentruy', 'fr'),
    ('code:600:LSXK', 'Benken', 'fr'),
    ('code:600:LSXR', 'Lodrino-Héliport', 'fr'),
    ('code:600:LSEA', 'Gstaad-Inn Grund', 'fr'),
    ('code:600:LSEY', 'Leysin', 'fr'),

    -- Italian
    ('code:600:LSZH', 'Zurigo', 'it'),
    ('code:600:NA2', 'Sembrancher', 'it'),
    ('code:600:LSGY', 'Yverdon', 'it'),
    ('code:600:LSTS', 'St. Stephan', 'it'),
    ('code:600:LSZJ', 'Courtelary', 'it'),
    ('code:600:LSTR', 'Montricher', 'it'),
    ('code:600:LSTO', 'Môtiers', 'it'),
    ('code:600:LSPU', 'Münster', 'it'),
    ('code:600:LSZA', 'Lugano-Agno', 'it'),
    ('code:600:LSZD', 'Ascona', 'it'),
    ('code:600:LSPM', 'Ambrì', 'it'),
    ('code:600:LSPA', 'Amlikon', 'it'),
    ('code:600:LSZE', 'Bad Ragaz', 'it'),
    ('code:600:LSTB', 'Bellechasse', 'it'),
    ('code:600:LSPL', 'Langenthal', 'it'),
    ('code:600:LSZT', 'Lommis', 'it'),
    ('code:600:LSZR', 'San Gallo-Altenrhein', 'it'),
    ('code:600:LSWS', 'Schwarzsee', 'it'),
    ('code:600:LSZM', 'Mollis', 'it'),
    ('code:600:LSPK', 'Hasenstrick', 'it'),
    ('code:600:LSXB', 'Balzers', 'it'),
    ('code:600:LSGC', 'La Chaux-de-Fonds-Les Eplatures', 'it'),
    ('code:600:LSGP', 'La Côte', 'it'),
    ('code:600:LSGL', 'Losanna-La Blécherette', 'it'),
    ('code:600:LSZB', 'Berna-Belp', 'it'),
    ('code:600:LSGB', 'Bex', 'it'),
    ('code:600:LSZO', 'Lucerna-Beromünster', 'it'),
    ('code:600:LSZF', 'Birrfeld', 'it'),
    ('code:600:LSZQ', 'Bressaucourt', 'it'),
    ('code:600:LSZU', 'Buttwil', 'it'),
    ('code:600:NA1', 'Davos', 'it'),
    ('code:600:LSPD', 'Dittingen', 'it'),
    ('code:600:LSXU', 'Untervaz', 'it'),
    ('code:600:LSPV', 'Wangen-Lachen', 'it'),
    ('code:600:LSPH', 'Winterthur', 'it'),
    ('code:600:LSGE', 'Ecuvillens', 'it'),
    ('code:600:LSME', 'Emmen', 'it'),
    ('code:600:LSXE', 'Erstfeld', 'it'),
    ('code:600:LSZI', 'Fricktal-Schupfart', 'it'),
    ('code:600:LSGG', 'Ginevra', 'it'),
    ('code:600:LSGN', 'Neuchâtel', 'it'),
    ('code:600:LSEG', 'Gampel', 'it'),
    ('code:600:LSXO', 'Gossau', 'it'),
    ('code:600:LSZN', 'Hausen a.A.', 'it'),
    ('code:600:LSZG', 'Grenchen', 'it'),
    ('code:600:LSGT', 'Gruyères', 'it'),
    ('code:600:LSPO', 'Olten', 'it'),
    ('code:600:LSXG', 'Gsteigwiler', 'it'),
    ('code:600:LSXN', 'Haltikon', 'it'),
    ('code:600:LSXH', 'Holziken', 'it'),
    ('code:600:LSXI', 'Interlaken', 'it'),
    ('code:600:LSPG', 'Kägiswil', 'it'),
    ('code:600:LSZX', 'Schänis', 'it'),
    ('code:600:LSXL', 'Lauterbrunnen', 'it'),
    ('code:600:LSZP', 'Bienne-Kappelen', 'it'),
    ('code:600:LSTA', 'Raron-Aerodromo', 'it'),
    ('code:600:LSER', 'Raron-Eliporto', 'it'),
    ('code:600:LSZL', 'Locarno', 'it'),
    ('code:600:LSML', 'Lodrino-Aerodromo', 'it'),
    ('code:600:LSXP', 'Pfaffnau', 'it'),
    ('code:600:LSGR', 'Reichenbach', 'it'),
    ('code:600:LSGK', 'Saanen', 'it'),
    ('code:600:LSZS', 'Samedan', 'it'),
    ('code:600:LSXV', 'San Vittore', 'it'),
    ('code:600:LSPF', 'Sciaffusa', 'it'),
    ('code:600:LSWL', 'Lauberhorn', 'it'),
    ('code:600:LSXC', 'Schattenhalb', 'it'),
    ('code:600:LSXS', 'Schindellegi', 'it'),
    ('code:600:LSGS', 'Sion', 'it'),
    ('code:600:LSZV', 'Sitterdorf', 'it'),
    ('code:600:LSZK', 'Speck-Fehraltorf', 'it'),
    ('code:600:LSXM', 'St. Moritz', 'it'),
    ('code:600:LSXA', 'Tavanasa', 'it'),
    ('code:600:LSZW', 'Thun', 'it'),
    ('code:600:LSPN', 'Triengen', 'it'),
    ('code:600:LSZC', 'Buochs', 'it'),
    ('code:600:LSXT', 'Trogen', 'it'),
    ('code:600:LSXW', 'Würenlingen', 'it'),
    ('code:600:LSEZ', 'Zermatt', 'it'),
    ('code:600:LSMP', 'Payerne', 'it'),
    ('code:600:LSTZ', 'Zweisimmen', 'it'),
    ('code:600:LSEC', 'Collombey-Muraz', 'it'),
    ('code:600:LSWB', 'Blumenstein', 'it'),
    ('code:600:LSWM', 'Männlichen', 'it'),
    ('code:600:LSXD', 'Domat-Ems', 'it'),
    ('code:600:LSZY', 'Porrentruy', 'it'),
    ('code:600:LSXK', 'Benken', 'it'),
    ('code:600:LSXR', 'Lodrino-Eliporto', 'it'),
    ('code:600:LSEA', 'Gstaad-Inn Grund', 'it'),
    ('code:600:LSEY', 'Leysin', 'it')
;
