insert into alma.c_cli (c_cli_id, bezeichnung, c_status)
values
    (25002, 'Branche PFAS-Feuerlösch-Standort', true),
    (500, 'PFAS-Typ', true),
    (501, 'PFAS-haltiges Löschmittel', true),
    (502, 'PFAS-freies Löschmittel', true),
    (503, 'Löschschaum-Einsatz', true),
    (504, 'Häufigkeit der Nutzung Handfeuerlöscher', true),
    (505, 'Häufigkeit der Nutzung Beimischer', true),
    (506, 'Häufigkeit der Nutzung Tanklöscher', true)
;

insert into alma.cod (c_cli_id, code, bemerkungen)
values
    (25002, '6455', 'Werkstatt für Feuerlöscher'),
    (25002, '9133', 'Feuerwehr'),
    (25002, '9134', 'Übungsanlage für Brandbekämpfung'),
    (25002, '9142', 'Zivilschutz'),
    (25002, '9811', 'Verkehrsunfall'),
    (25002, '9812', 'Betriebsunfall'),
    (500, 'magazin', 'Magazin'),
    (500, 'ua', 'Übungsanlage für Brandbekämpfung'),
    (500, 'us', 'Übungsplatz für Brandbekämpfung'),
    (500, 'brand', 'Brandereignis'),
    (500, 'schaum', 'Löschschaumanlage'),
    (501, 'fffp', 'FFFP'),
    (501, 'fps', 'FPS'),
    (501, 'afff', 'AFFF'),
    (501, 'afff-ar', 'AFFF/AR'),
    (501, 'fp', 'FP'),
    (501, 'fp-ar', 'FP/AR'),
    (502, 'a', 'Class A'),
    (502, 'mbs', 'MBS'),
    (502, 'p', 'P'),
    (502, 'fff', 'FFF'),
    (502, 'fff-ar', 'FFF/AR'),
    (503, 'hand', 'Handfeuerlöscher'),
    (503, 'bei', 'Beimischer'),
    (503, 'tank', 'Tanklöschfahrzeug'),
    (504, 'nie', 'Nie'),
    (504, 'einmal', 'einmal'),
    (504, 'wenig', 'wenige Male'),
    (504, 'regel', 'regelmässig'),
    (505, 'nie', 'Nie'),
    (505, 'einmal', 'einmal'),
    (505, 'wenig', 'wenige Male'),
    (505, 'regel', 'regelmässig'),
    (506, 'nie', 'Nie'),
    (506, 'einmal', 'einmal'),
    (506, 'wenig', 'wenige Male'),
    (506, 'regel', 'regelmässig'),
    (25, '6445', 'Werkstatt für Feuerlöscher')
;

insert into alma.translations (msgid, msgstr, locale)
values
    ('code:25002:6455', '6455: Werkstatt für Feuerlöscher', 'de'),
    ('code:25002:6455', '6455: Atelier de réparation d''extincteurs', 'fr'),
    ('code:25002:6455', '6455: Officina per estintori', 'it'),
    ('code:25002:9133', '9133: Feuerwehr', 'de'),
    ('code:25002:9133', '9133: Pompiers', 'fr'),
    ('code:25002:9133', '9133: Vigili del fuoco', 'it'),
    ('code:25002:9134', '9134: Übungsanlage für Brandbekämpfung', 'de'),
    ('code:25002:9134', '9134: Centre d''entraînement à la lutte contre l''incendie', 'fr'),
    ('code:25002:9134', '9134: Centro di addestramento per la lotta antincendio', 'it'),
    ('code:25002:9142', '9142: Zivilschutz', 'de'),
    ('code:25002:9142', '9142: Protection civile', 'fr'),
    ('code:25002:9142', '9142: Protezione civile', 'it'),
    ('code:25002:9811', '9811: Verkehrsunfall', 'de'),
    ('code:25002:9811', '9811: Accident de la circulation', 'fr'),
    ('code:25002:9811', '9811: Incidente stradale', 'it'),
    ('code:25002:9812', '9812: Betriebsunfall', 'de'),
    ('code:25002:9812', '9812: Accident d''exploitation', 'fr'),
    ('code:25002:9812', '9812: Incidente sul lavoro', 'it'),
    ('code:500:magazin', 'Magazin', 'de'),
    ('code:500:magazin', 'Magasin', 'fr'),
    ('code:500:magazin', 'Magazzino', 'it'),
    ('code:500:ua', 'Übungsanlage für Brandbekämpfung', 'de'),
    ('code:500:ua', 'Centre d''entraînement à la lutte contre l''incendie', 'fr'),
    ('code:500:ua', 'Centro di addestramento per la lotta antincendio', 'it'),
    ('code:500:us', 'Übungsplatz für Brandbekämpfung', 'de'),
    ('code:500:us', 'Place d''entraînement à la lutte contre l''incendie', 'fr'),
    ('code:500:us', 'Area di addestramento per la lotta antincendio', 'it'),
    ('code:500:brand', 'Brandereignis', 'de'),
    ('code:500:brand', 'Événement d''incendie', 'fr'),
    ('code:500:brand', 'Evento di incendio', 'it'),
    ('code:500:schaum', 'Löschschaumanlage', 'de'),
    ('code:500:schaum', 'Installation de mousse extinctrice', 'fr'),
    ('code:500:schaum', 'Impianto di schiuma estinguente', 'it'),
    ('code:501:fffp', 'FFFP', 'de'),
    ('code:501:fffp', 'FFFP', 'fr'),
    ('code:501:fffp', 'FFFP', 'it'),
    ('code:501:fps', 'FPS', 'de'),
    ('code:501:fps', 'FPS', 'fr'),
    ('code:501:fps', 'FPS', 'it'),
    ('code:501:afff', 'AFFF', 'de'),
    ('code:501:afff', 'AFFF', 'fr'),
    ('code:501:afff', 'AFFF', 'it'),
    ('code:501:afff-ar', 'AFFF/AR', 'de'),
    ('code:501:afff-ar', 'AFFF/AR', 'fr'),
    ('code:501:afff-ar', 'AFFF/AR', 'it'),
    ('code:501:fp', 'FP', 'de'),
    ('code:501:fp', 'FP', 'fr'),
    ('code:501:fp', 'FP', 'it'),
    ('code:501:fp-ar', 'FP/AR', 'de'),
    ('code:501:fp-ar', 'FP/AR', 'fr'),
    ('code:501:fp-ar', 'FP/AR', 'it'),
    ('code:502:a', 'Class A', 'de'),
    ('code:502:a', 'Classe A', 'fr'),
    ('code:502:a', 'Classe A', 'it'),
    ('code:502:mbs', 'MBS', 'de'),
    ('code:502:mbs', 'MBS', 'fr'),
    ('code:502:mbs', 'MBS', 'it'),
    ('code:502:p', 'P', 'de'),
    ('code:502:p', 'P', 'fr'),
    ('code:502:p', 'P', 'it'),
    ('code:502:fff', 'FFF', 'de'),
    ('code:502:fff', 'FFF', 'fr'),
    ('code:502:fff', 'FFF', 'it'),
    ('code:502:fff-ar', 'FFF/AR', 'de'),
    ('code:502:fff-ar', 'FFF/AR', 'fr'),
    ('code:502:fff-ar', 'FFF/AR', 'it'),
    ('code:503:hand', 'Handfeuerlöscher', 'de'),
    ('code:503:hand', 'Extincteurs à main', 'fr'),
    ('code:503:hand', 'Estintore portatile', 'it'),
    ('code:503:bei', 'Beimischer', 'de'),
    ('code:503:bei', 'Mélangeur', 'fr'),
    ('code:503:bei', 'Miscelatore', 'it'),
    ('code:503:tank', 'Tanklöschfahrzeug', 'de'),
    ('code:503:tank', 'Véhicule-citerne d’extinction', 'fr'),
    ('code:503:tank', 'Veicolo di spegnimento', 'it'),
    ('code:504:nie', 'Nie', 'de'),
    ('code:504:nie', 'Jamais', 'fr'),
    ('code:504:nie', 'Mai', 'it'),
    ('code:504:einmal', 'Einmal in diesem Nutzungszeitraum', 'de'),
    ('code:504:einmal', 'Une fois pendant cette période d''utilisation', 'fr'),
    ('code:504:einmal', 'Una volta in questo periodo di utilizzo', 'it'),
    ('code:504:wenig', 'Wenige Male (weniger als 5 Mal in diesem Nutzungszeitraum)', 'de'),
    ('code:504:wenig', 'Quelques fois (moins de 5 fois pendant cette période d''utilisation)', 'fr'),
    ('code:504:wenig', 'Poche volte (meno di 5 volte in questo periodo di utilizzo)', 'it'),
    ('code:504:regel', 'Regelmässig (5 Mal oder mehr in diesem Nutzungszeitraum)', 'de'),
    ('code:504:regel', 'Régulièrement (5 fois ou plus pendant cette période d''utilisation)', 'fr'),
    ('code:504:regel', 'Regolarmente (5 volte o più in questo periodo di utilizzo)', 'it'),
    ('code:505:nie', 'Nie', 'de'),
    ('code:505:nie', 'Jamais', 'fr'),
    ('code:505:nie', 'Mai', 'it'),
    ('code:505:einmal', 'Einmal in diesem Nutzungszeitraum', 'de'),
    ('code:505:einmal', 'Une fois pendant cette période d''utilisation', 'fr'),
    ('code:505:einmal', 'Una volta in questo periodo di utilizzo', 'it'),
    ('code:505:wenig', 'Wenige Male (weniger als 5 Mal in diesem Nutzungszeitraum)', 'de'),
    ('code:505:wenig', 'Quelques fois (moins de 5 fois pendant cette période d''utilisation)', 'fr'),
    ('code:505:wenig', 'Poche volte (meno di 5 volte in questo periodo di utilizzo)', 'it'),
    ('code:505:regel', 'Regelmässig (5 Mal oder mehr in diesem Nutzungszeitraum)', 'de'),
    ('code:505:regel', 'Régulièrement (5 fois ou plus pendant cette période d''utilisation)', 'fr'),
    ('code:505:regel', 'Regolarmente (5 volte o più in questo periodo di utilizzo)', 'it'),
    ('code:506:nie', 'Nie', 'de'),
    ('code:506:nie', 'Jamais', 'fr'),
    ('code:506:nie', 'Mai', 'it'),
    ('code:506:einmal', 'Einmal in diesem Nutzungszeitraum', 'de'),
    ('code:506:einmal', 'Une fois pendant cette période d''utilisation', 'fr'),
    ('code:506:einmal', 'Una volta in questo periodo di utilizzo', 'it'),
    ('code:506:wenig', 'Wenige Male (weniger als 5 Mal in diesem Nutzungszeitraum)', 'de'),
    ('code:506:wenig', 'Quelques fois (moins de 5 fois pendant cette période d''utilisation)', 'fr'),
    ('code:506:wenig', 'Poche volte (meno di 5 volte in questo periodo di utilizzo)', 'it'),
    ('code:506:regel', 'Regelmässig (5 Mal oder mehr in diesem Nutzungszeitraum)', 'de'),
    ('code:506:regel', 'Régulièrement (5 fois ou plus pendant cette période d''utilisation)', 'fr'),
    ('code:506:regel', 'Regolarmente (5 volte o più in questo periodo di utilizzo)', 'it'),
    ('code:25:6445', 'Werkstatt für Feuerlöscher', 'de'),
    ('code:25:6445', 'Atelier de réparation d''extincteurs', 'fr'),
    ('code:25:6445', 'Officina per estintori', 'it')
;

insert into alma.cod (c_cli_id, code, c_status) values
    (63, '06', true)
;

insert into alma.translations (msgid, msgstr, locale) values
    ('code:63:06', 'PFAS-Feuerlösch-Standorte', 'de'),
    ('code:63:06', 'Emplacements d’extinction PFAS', 'fr'),
    ('code:63:06', 'Luoghi di installazione per estinzioni PFAS', 'it')
;
